/**
 * 游戏注册库 — 22款高留存休闲小游戏
 * 12款经典 + 10款全球爆款新品
 * 每款游戏都是市场最受欢迎级别，深度开发
 */

export interface Game {
  id: string;
  name: string;
  description: string;
  path: string;
  icon: string; // emoji
  category: "puzzle" | "arcade" | "brain" | "daily" | "reflex" | "strategy" | "casual",
  categoryName: string;
  color: string; // tailwind gradient
  tags: string[];
  difficulty: "easy" | "medium" | "hard";
  avgSessionMin: number; // 平均单局分钟数
  hasLeaderboard: boolean;
  hasDailyChallenge: boolean;
  retentionScore: number; // 1-10 留存评分
}

export const games: Game[] = [
  {
    id: "2048",
    name: "2048",
    description: "经典数字合并游戏，滑动方块将相同数字合并，目标达到2048甚至更高！简单上手，极度上瘾。",
    path: "/games/2048",
    icon: "🔢",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-amber-500 to-orange-500",
    tags: ["2048", "数字合并", "益智", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 10,
  },
  {
    id: "snake",
    name: "贪吃蛇",
    description: "经典贪吃蛇游戏，控制蛇吃食物变长，撞墙或自身即结束。考验反应与策略！",
    path: "/games/snake",
    icon: "🐍",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-green-500 to-emerald-500",
    tags: ["贪吃蛇", "经典", "街机", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "typing-test",
    name: "打字速度测试",
    description: "测试你的打字速度！限时60秒，统计WPM（每分钟字数）和准确率。天然适合PK对比。",
    path: "/games/typing-test",
    icon: "⌨️",
    category: "reflex",
    categoryName: "反应训练",
    color: "from-blue-500 to-cyan-500",
    tags: ["打字", "速度测试", "WPM", "排行榜"],
    difficulty: "medium",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 9,
  },
  {
    id: "memory-match",
    name: "记忆翻牌",
    description: "翻开卡片找到相同图案的配对，用最少步数和最短时间完成全部配对。锻炼短时记忆！",
    path: "/games/memory-match",
    icon: "🃏",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-purple-500 to-violet-500",
    tags: ["记忆", "翻牌", "配对", "脑力"],
    difficulty: "easy",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 7,
  },
  {
    id: "reaction-test",
    name: "反应力测试",
    description: "测试你的反应速度！屏幕变绿时立即点击，测量毫秒级反应时间。谁更快？",
    path: "/games/reaction-test",
    icon: "⚡",
    category: "reflex",
    categoryName: "反应训练",
    color: "from-yellow-500 to-amber-500",
    tags: ["反应力", "速度", "毫秒", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 1,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 8,
  },
  {
    id: "stroop-test",
    name: "色字干扰测试",
    description: "Stroop效应测试：选择文字的颜色而非字义。看似简单实则烧脑，测测你的抗干扰能力！",
    path: "/games/stroop-test",
    icon: "🎨",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-pink-500 to-rose-500",
    tags: ["Stroop", "色字", "脑力", "注意力"],
    difficulty: "medium",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 8,
  },
  {
    id: "minesweeper",
    name: "扫雷",
    description: "经典Windows扫雷游戏！根据数字推理避开雷区，标记所有地雷即可获胜。",
    path: "/games/minesweeper",
    icon: "💣",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-gray-500 to-slate-500",
    tags: ["扫雷", "逻辑", "推理", "经典"],
    difficulty: "hard",
    avgSessionMin: 5,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 7,
  },
  {
    id: "tic-tac-toe",
    name: "井字棋AI对战",
    description: "经典井字棋（三连棋），挑战无敌AI！AI使用Minimax算法，你能逼平甚至战胜它吗？",
    path: "/games/tic-tac-toe",
    icon: "⭕",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-indigo-500 to-blue-500",
    tags: ["井字棋", "AI对战", "策略", "Minimax"],
    difficulty: "easy",
    avgSessionMin: 2,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 6,
  },
  {
    id: "daily-sudoku",
    name: "每日数独",
    description: "每天一题经典数独，全员同题！9×9格子填入1-9，每行每列每宫不重复。Wordle式每日挑战。",
    path: "/games/daily-sudoku",
    icon: "📊",
    category: "daily",
    categoryName: "每日挑战",
    color: "from-teal-500 to-cyan-500",
    tags: ["数独", "每日", "逻辑", "同题PK"],
    difficulty: "hard",
    avgSessionMin: 8,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 10,
  },
  {
    id: "color-guess",
    name: "颜色辨别测试",
    description: "在一堆相同颜色中找出色差不同的那一块！随着关卡推进色差越来越小，你能过几关？",
    path: "/games/color-guess",
    icon: "🌈",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-fuchsia-500 to-pink-500",
    tags: ["颜色", "辨别", "视觉", "关卡"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "number-memory",
    name: "数字记忆挑战",
    description: "记忆一串数字然后输入！数字长度逐级增加，从3位到20位，你的记忆极限在哪里？",
    path: "/games/number-memory",
    icon: "🧠",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-violet-500 to-purple-500",
    tags: ["记忆", "数字", "脑力", "极限"],
    difficulty: "medium",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "aim-trainer",
    name: "瞄准训练器",
    description: "30秒内点击尽可能多的目标！训练你的鼠标精准度和速度。FPS玩家必备训练工具。",
    path: "/games/aim-trainer",
    icon: "🎯",
    category: "reflex",
    categoryName: "反应训练",
    color: "from-red-500 to-orange-500",
    tags: ["瞄准", "射击", "反应", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 1,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 7,
  },

  /* ===== 10款全球爆款新品 ===== */

  {
    id: "suika-merge",
    name: "合成大西瓜",
    description: "全球爆火的物理合成游戏！相同水果碰撞合成更大的水果，最终目标合成大西瓜。物理引擎+策略，上瘾度爆表。",
    path: "/games/suika-merge",
    icon: "🍉",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-green-400 to-lime-500",
    tags: ["合成西瓜", "物理", "合并", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 10,
  },
  {
    id: "tetris",
    name: "俄罗斯方块",
    description: "永恒经典的方块消除游戏！旋转、移动、消除整行，速度越来越快。全球销量最高的游戏类型。",
    path: "/games/tetris",
    icon: "📦",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-cyan-400 to-blue-500",
    tags: ["俄罗斯方块", "消除", "经典", "排行榜"],
    difficulty: "medium",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 10,
  },
  {
    id: "brick-breaker",
    name: "弹球消除",
    description: "经典打砖块游戏！控制挡板让弹球弹射消除所有砖块，多种砖块类型和道具。物理弹射的纯粹爽感。",
    path: "/games/brick-breaker",
    icon: "🧱",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-orange-400 to-red-500",
    tags: ["打砖块", "弹球", "物理", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "doodle-jump",
    name: "无尽跳跃",
    description: "控制角色不断向上跳跃，踩中平台上升，躲避障碍。掉落即结束，比比谁跳得更高！全球超火爆跑酷类型。",
    path: "/games/doodle-jump",
    icon: "🦘",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-emerald-400 to-teal-500",
    tags: ["跳跃", "跑酷", "无尽", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "rhythm-tap",
    name: "节奏大师",
    description: "音符从天而降，在恰当时机点击获得完美判定！连击系统+精准评分，体验音游的极致快感。",
    path: "/games/rhythm-tap",
    icon: "🎵",
    category: "reflex",
    categoryName: "反应训练",
    color: "from-purple-400 to-fuchsia-500",
    tags: ["节奏", "音乐", "连击", "排行榜"],
    difficulty: "medium",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 9,
  },
  {
    id: "gomoku",
    name: "五子棋AI",
    description: "15×15棋盘，五子连珠获胜！AI采用模式识别+威胁评估，提供三档难度。经典策略对战的网页巅峰。",
    path: "/games/gomoku",
    icon: "⚫",
    category: "strategy",
    categoryName: "策略对战",
    color: "from-slate-400 to-gray-600",
    tags: ["五子棋", "AI对战", "策略", "棋类"],
    difficulty: "hard",
    avgSessionMin: 5,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "bubble-shooter",
    name: "泡泡龙",
    description: "瞄准发射彩色泡泡，3个以上同色相连即可消除！经典消除玩法，简单上手极度上瘾。",
    path: "/games/bubble-shooter",
    icon: "🫧",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-sky-400 to-indigo-500",
    tags: ["泡泡龙", "射击", "消除", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "idle-clicker",
    name: "放置点击",
    description: "点击赚取积分，购买自动升级实现指数增长！离线也能收益，打开就有奖励。放置类游戏的经典代表。",
    path: "/games/idle-clicker",
    icon: "🍪",
    category: "casual",
    categoryName: "休闲放置",
    color: "from-amber-400 to-yellow-500",
    tags: ["放置", "点击", "升级", "离线收益"],
    difficulty: "easy",
    avgSessionMin: 10,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 10,
  },
  {
    id: "sliding-puzzle",
    name: "数字华容道",
    description: "经典15数字华容道！滑动数字方块排列1-15顺序，用最少步数和最短时间完成。每日一题全员PK。",
    path: "/games/sliding-puzzle",
    icon: "🔢",
    category: "daily",
    categoryName: "每日挑战",
    color: "from-rose-400 to-pink-500",
    tags: ["华容道", "滑动", "拼图", "每日"],
    difficulty: "medium",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 8,
  },
  {
    id: "one-line-draw",
    name: "一笔画",
    description: "用一笔画完整个图形，不重复不遗漏！经典欧拉路径谜题， hundreds of关卡由易到难。最强大脑同款。",
    path: "/games/one-line-draw",
    icon: "✏️",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-violet-400 to-purple-500",
    tags: ["一笔画", "欧拉路径", "逻辑", "关卡"],
    difficulty: "medium",
    avgSessionMin: 4,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
];

export function getGameById(id: string): Game | undefined {
  return games.find((g) => g.id === id);
}

export function getGamesByCategory(category: string): Game[] {
  return games.filter((g) => g.category === category);
}

export const gameCategories = [
  { id: "all", name: "全部游戏", icon: "🎮" },
  { id: "puzzle", name: "益智消除", icon: "🧩" },
  { id: "arcade", name: "经典街机", icon: "🕹️" },
  { id: "brain", name: "脑力训练", icon: "🧠" },
  { id: "daily", name: "每日挑战", icon: "📅" },
  { id: "reflex", name: "反应训练", icon: "⚡" },
  { id: "strategy", name: "策略对战", icon: "♟️" },
  { id: "casual", name: "休闲放置", icon: "🍃" },
];
