/**
 * 游戏注册库 — 42款高留存休闲小游戏
 * 12款经典 + 10款全球爆款 + 20款2026新品爆款
 * 每款游戏都是市场最受欢迎级别，深度开发
 */

export interface Game {
  id: string;
  name: string;
  description: string;
  path: string;
  icon: string; // emoji
  category: "puzzle" | "arcade" | "brain" | "daily" | "reflex" | "strategy" | "casual" | "io" | "physics" | "meme" | "simulation",
  categoryName: string;
  color: string; // tailwind gradient
  tags: string[];
  difficulty: "easy" | "medium" | "hard";
  avgSessionMin: number; // 平均单局分钟数
  hasLeaderboard: boolean;
  hasDailyChallenge: boolean;
  retentionScore: number; // 1-10 留存评分
}

export const games: Game[] = [
  {
    id: "2048",
    name: "2048",
    description: "经典数字合并游戏，滑动方块将相同数字合并，目标达到2048甚至更高！简单上手，极度上瘾。",
    path: "/games/2048",
    icon: "🔢",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-amber-500 to-orange-500",
    tags: ["2048", "数字合并", "益智", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 10,
  },
  {
    id: "snake",
    name: "贪吃蛇",
    description: "经典贪吃蛇游戏，控制蛇吃食物变长，撞墙或自身即结束。考验反应与策略！",
    path: "/games/snake",
    icon: "🐍",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-green-500 to-emerald-500",
    tags: ["贪吃蛇", "经典", "街机", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "typing-test",
    name: "打字速度测试",
    description: "测试你的打字速度！限时60秒，统计WPM（每分钟字数）和准确率。天然适合PK对比。",
    path: "/games/typing-test",
    icon: "⌨️",
    category: "reflex",
    categoryName: "反应训练",
    color: "from-blue-500 to-cyan-500",
    tags: ["打字", "速度测试", "WPM", "排行榜"],
    difficulty: "medium",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 9,
  },
  {
    id: "memory-match",
    name: "记忆翻牌",
    description: "翻开卡片找到相同图案的配对，用最少步数和最短时间完成全部配对。锻炼短时记忆！",
    path: "/games/memory-match",
    icon: "🃏",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-purple-500 to-violet-500",
    tags: ["记忆", "翻牌", "配对", "脑力"],
    difficulty: "easy",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 7,
  },
  {
    id: "reaction-test",
    name: "反应力测试",
    description: "测试你的反应速度！屏幕变绿时立即点击，测量毫秒级反应时间。谁更快？",
    path: "/games/reaction-test",
    icon: "⚡",
    category: "reflex",
    categoryName: "反应训练",
    color: "from-yellow-500 to-amber-500",
    tags: ["反应力", "速度", "毫秒", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 1,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 8,
  },
  {
    id: "stroop-test",
    name: "色字干扰测试",
    description: "Stroop效应测试：选择文字的颜色而非字义。看似简单实则烧脑，测测你的抗干扰能力！",
    path: "/games/stroop-test",
    icon: "🎨",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-pink-500 to-rose-500",
    tags: ["Stroop", "色字", "脑力", "注意力"],
    difficulty: "medium",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 8,
  },
  {
    id: "minesweeper",
    name: "扫雷",
    description: "经典Windows扫雷游戏！根据数字推理避开雷区，标记所有地雷即可获胜。",
    path: "/games/minesweeper",
    icon: "💣",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-gray-500 to-slate-500",
    tags: ["扫雷", "逻辑", "推理", "经典"],
    difficulty: "hard",
    avgSessionMin: 5,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 7,
  },
  {
    id: "tic-tac-toe",
    name: "井字棋AI对战",
    description: "经典井字棋（三连棋），挑战无敌AI！AI使用Minimax算法，你能逼平甚至战胜它吗？",
    path: "/games/tic-tac-toe",
    icon: "⭕",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-indigo-500 to-blue-500",
    tags: ["井字棋", "AI对战", "策略", "Minimax"],
    difficulty: "easy",
    avgSessionMin: 2,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 6,
  },
  {
    id: "daily-sudoku",
    name: "每日数独",
    description: "每天一题经典数独，全员同题！9×9格子填入1-9，每行每列每宫不重复。Wordle式每日挑战。",
    path: "/games/daily-sudoku",
    icon: "📊",
    category: "daily",
    categoryName: "每日挑战",
    color: "from-teal-500 to-cyan-500",
    tags: ["数独", "每日", "逻辑", "同题PK"],
    difficulty: "hard",
    avgSessionMin: 8,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 10,
  },
  {
    id: "color-guess",
    name: "颜色辨别测试",
    description: "在一堆相同颜色中找出色差不同的那一块！随着关卡推进色差越来越小，你能过几关？",
    path: "/games/color-guess",
    icon: "🌈",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-fuchsia-500 to-pink-500",
    tags: ["颜色", "辨别", "视觉", "关卡"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "number-memory",
    name: "数字记忆挑战",
    description: "记忆一串数字然后输入！数字长度逐级增加，从3位到20位，你的记忆极限在哪里？",
    path: "/games/number-memory",
    icon: "🧠",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-violet-500 to-purple-500",
    tags: ["记忆", "数字", "脑力", "极限"],
    difficulty: "medium",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "aim-trainer",
    name: "瞄准训练器",
    description: "30秒内点击尽可能多的目标！训练你的鼠标精准度和速度。FPS玩家必备训练工具。",
    path: "/games/aim-trainer",
    icon: "🎯",
    category: "reflex",
    categoryName: "反应训练",
    color: "from-red-500 to-orange-500",
    tags: ["瞄准", "射击", "反应", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 1,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 7,
  },

  /* ===== 10款全球爆款新品 ===== */

  {
    id: "suika-merge",
    name: "合成大西瓜",
    description: "全球爆火的物理合成游戏！相同水果碰撞合成更大的水果，最终目标合成大西瓜。物理引擎+策略，上瘾度爆表。",
    path: "/games/suika-merge",
    icon: "🍉",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-green-400 to-lime-500",
    tags: ["合成西瓜", "物理", "合并", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 10,
  },
  {
    id: "tetris",
    name: "俄罗斯方块",
    description: "永恒经典的方块消除游戏！旋转、移动、消除整行，速度越来越快。全球销量最高的游戏类型。",
    path: "/games/tetris",
    icon: "📦",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-cyan-400 to-blue-500",
    tags: ["俄罗斯方块", "消除", "经典", "排行榜"],
    difficulty: "medium",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 10,
  },
  {
    id: "brick-breaker",
    name: "弹球消除",
    description: "经典打砖块游戏！控制挡板让弹球弹射消除所有砖块，多种砖块类型和道具。物理弹射的纯粹爽感。",
    path: "/games/brick-breaker",
    icon: "🧱",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-orange-400 to-red-500",
    tags: ["打砖块", "弹球", "物理", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "doodle-jump",
    name: "无尽跳跃",
    description: "控制角色不断向上跳跃，踩中平台上升，躲避障碍。掉落即结束，比比谁跳得更高！全球超火爆跑酷类型。",
    path: "/games/doodle-jump",
    icon: "🦘",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-emerald-400 to-teal-500",
    tags: ["跳跃", "跑酷", "无尽", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "rhythm-tap",
    name: "节奏大师",
    description: "音符从天而降，在恰当时机点击获得完美判定！连击系统+精准评分，体验音游的极致快感。",
    path: "/games/rhythm-tap",
    icon: "🎵",
    category: "reflex",
    categoryName: "反应训练",
    color: "from-purple-400 to-fuchsia-500",
    tags: ["节奏", "音乐", "连击", "排行榜"],
    difficulty: "medium",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 9,
  },
  {
    id: "gomoku",
    name: "五子棋AI",
    description: "15×15棋盘，五子连珠获胜！AI采用模式识别+威胁评估，提供三档难度。经典策略对战的网页巅峰。",
    path: "/games/gomoku",
    icon: "⚫",
    category: "strategy",
    categoryName: "策略对战",
    color: "from-slate-400 to-gray-600",
    tags: ["五子棋", "AI对战", "策略", "棋类"],
    difficulty: "hard",
    avgSessionMin: 5,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 8,
  },
  {
    id: "bubble-shooter",
    name: "泡泡龙",
    description: "瞄准发射彩色泡泡，3个以上同色相连即可消除！经典消除玩法，简单上手极度上瘾。",
    path: "/games/bubble-shooter",
    icon: "🫧",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-sky-400 to-indigo-500",
    tags: ["泡泡龙", "射击", "消除", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "idle-clicker",
    name: "放置点击",
    description: "点击赚取积分，购买自动升级实现指数增长！离线也能收益，打开就有奖励。放置类游戏的经典代表。",
    path: "/games/idle-clicker",
    icon: "🍪",
    category: "casual",
    categoryName: "休闲放置",
    color: "from-amber-400 to-yellow-500",
    tags: ["放置", "点击", "升级", "离线收益"],
    difficulty: "easy",
    avgSessionMin: 10,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 10,
  },
  {
    id: "sliding-puzzle",
    name: "数字华容道",
    description: "经典15数字华容道！滑动数字方块排列1-15顺序，用最少步数和最短时间完成。每日一题全员PK。",
    path: "/games/sliding-puzzle",
    icon: "🔢",
    category: "daily",
    categoryName: "每日挑战",
    color: "from-rose-400 to-pink-500",
    tags: ["华容道", "滑动", "拼图", "每日"],
    difficulty: "medium",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 8,
  },
  {
    id: "one-line-draw",
    name: "一笔画",
    description: "用一笔画完整个图形，不重复不遗漏！经典欧拉路径谜题， hundreds of关卡由易到难。最强大脑同款。",
    path: "/games/one-line-draw",
    icon: "✏️",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-violet-400 to-purple-500",
    tags: ["一笔画", "欧拉路径", "逻辑", "关卡"],
    difficulty: "medium",
    avgSessionMin: 4,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 8,
  },

  /* ===== 20款2026新品爆款（基于最近3个月全球热门排行榜） ===== */

  /* --- .io 多人竞技 (4款) --- */
  {
    id: "snake-arena",
    name: "蛇之竞技场",
    description: "Slither.io风格蛇之竞技场！控制蛇吃光点变长，撞击AI对手使其爆炸。单机模拟.io多人体验，全球最火爆类型。",
    path: "/games/snake-arena",
    icon: "🐉",
    category: "io",
    categoryName: "竞技对抗",
    color: "from-lime-400 to-green-500",
    tags: ["io", "蛇", "竞技", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 10,
  },
  {
    id: "black-hole",
    name: "黑洞吞噬",
    description: "Hole.io风格黑洞吞噬！控制黑洞移动，吞噬比你小的物体不断变大。从小石子到整栋大楼，吞噬一切！",
    path: "/games/black-hole",
    icon: "🕳️",
    category: "io",
    categoryName: "竞技对抗",
    color: "from-slate-600 to-gray-800",
    tags: ["io", "黑洞", "吞噬", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "territory-war",
    name: "领地战争",
    description: "Paper.io风格领地争夺！画出闭环圈占领地，小心别被对手切断尾巴。AI对手智能围堵，策略与速度的较量。",
    path: "/games/territory-war",
    icon: "🗺️",
    category: "io",
    categoryName: "竞技对抗",
    color: "from-cyan-400 to-blue-500",
    tags: ["io", "领地", "策略", "排行榜"],
    difficulty: "medium",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "battle-royale",
    name: "生存竞技场",
    description: " Battle Royale风格生存竞技！缩小安全区，消灭AI对手，最后存活者获胜。紧张刺激的缩圈生存体验。",
    path: "/games/battle-royale",
    icon: "💀",
    category: "io",
    categoryName: "竞技对抗",
    color: "from-red-500 to-rose-700",
    tags: ["io", "生存", "大逃杀", "排行榜"],
    difficulty: "hard",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },

  /* --- 合成/Merge (3款) --- */
  {
    id: "merge-bubbles",
    name: "合成泡泡",
    description: "瞄准发射泡泡，相同颜色碰撞合成更大泡泡！10级进化链，策略发射角度。合成消除的全新变体。",
    path: "/games/merge-bubbles",
    icon: "🔮",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-purple-400 to-indigo-500",
    tags: ["合成", "泡泡", "消除", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "merge-tower",
    name: "合成塔防",
    description: "合成相同防御塔升级火力，抵御一波波敌人进攻！策略合成+塔防双玩法，每波都是新挑战。",
    path: "/games/merge-tower",
    icon: "🏰",
    category: "strategy",
    categoryName: "策略对战",
    color: "from-amber-500 to-orange-600",
    tags: ["合成", "塔防", "策略", "升级"],
    difficulty: "medium",
    avgSessionMin: 6,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "chain-merge",
    name: "链式合成",
    description: "点击连通的同色方块进行链式消除合成！连得越多分数越高，合成连锁反应带来极致爽感。",
    path: "/games/chain-merge",
    icon: "🔗",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-teal-400 to-cyan-500",
    tags: ["合成", "连锁", "消除", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 8,
  },

  /* --- 物理/布偶 (3款) --- */
  {
    id: "ragdoll-launch",
    name: "布偶发射器",
    description: "Ragdoll Archers风格物理发射！调整角度和力度发射布偶人，击中靶心得分。搞笑物理效果，天然分享素材。",
    path: "/games/ragdoll-launch",
    icon: "🤸",
    category: "physics",
    categoryName: "物理搞笑",
    color: "from-pink-400 to-rose-500",
    tags: ["物理", "布偶", "发射", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },
  {
    id: "slice-cut",
    name: "切割大师",
    description: "Slice Master风格物理切割！用鼠标划线切割飞来的物体，精准切片得分。水果忍者+物理引擎的完美结合。",
    path: "/games/slice-cut",
    icon: "🔪",
    category: "physics",
    categoryName: "物理搞笑",
    color: "from-orange-400 to-red-500",
    tags: ["物理", "切割", "水果忍者", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 8,
  },
  {
    id: "stack-tower",
    name: "物理叠塔",
    description: "Stack风格物理叠塔！吊臂来回摆动，精准时机放下方块。偏移部分被切掉，越来越窄越来越难。",
    path: "/games/stack-tower",
    icon: "🏗️",
    category: "physics",
    categoryName: "物理搞笑",
    color: "from-indigo-400 to-blue-500",
    tags: ["物理", "叠塔", "精准", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 3,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },

  /* --- 梗/Brainrot (2款) --- */
  {
    id: "meme-tap",
    name: "梗图快打",
    description: "疯狂鸽子风格梗图反应游戏！热梗角色随机弹出，快速点击得分。2026年最火brainrot文化，天然社媒传播。",
    path: "/games/meme-tap",
    icon: "🫧",
    category: "meme",
    categoryName: "梗趣文化",
    color: "from-fuchsia-400 to-pink-500",
    tags: ["梗", "反应", "brainrot", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 2,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 9,
  },
  {
    id: "brainrot-match",
    name: "脑洞消消乐",
    description: "Brainrot角色三消游戏！交换相邻梗角色，三个以上同款消除。2026热梗文化+经典消除的病毒组合。",
    path: "/games/brainrot-match",
    icon: "🧪",
    category: "meme",
    categoryName: "梗趣文化",
    color: "from-violet-400 to-fuchsia-500",
    tags: ["梗", "三消", "brainrot", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },

  /* --- 放置/点击 (2款) --- */
  {
    id: "cookie-empire",
    name: "饼干帝国",
    description: "进阶版放置点击游戏！点击生产饼干，购买建筑自动产出，转生系统重置获永久加成。比经典放置更深度的数值系统。",
    path: "/games/cookie-empire",
    icon: "🍪",
    category: "casual",
    categoryName: "休闲放置",
    color: "from-amber-400 to-orange-500",
    tags: ["放置", "点击", "转生", "离线收益"],
    difficulty: "easy",
    avgSessionMin: 10,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 10,
  },
  {
    id: "space-idle",
    name: "星际放置",
    description: "太空主题放置游戏！殖民星球自动产能源，升级科技解锁新星球。从地球到银河系，放置征服宇宙。",
    path: "/games/space-idle",
    icon: "🪐",
    category: "casual",
    categoryName: "休闲放置",
    color: "from-indigo-500 to-purple-600",
    tags: ["放置", "太空", "殖民", "离线收益"],
    difficulty: "easy",
    avgSessionMin: 10,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 9,
  },

  /* --- 消除/三消 (2款) --- */
  {
    id: "gem-match",
    name: "宝石迷阵",
    description: "经典Bejeweled风格三消游戏！交换相邻宝石，三个以上同色消除连锁。限时模式+连击系统，消除爱好者的天堂。",
    path: "/games/gem-match",
    icon: "💎",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-cyan-400 to-teal-500",
    tags: ["三消", "宝石", "连锁", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: true,
    retentionScore: 9,
  },
  {
    id: "block-jigsaw",
    name: "方块拼图",
    description: "Wood Block Journey风格方块拼图！将不同形状的方块放入网格，填满整行整列即消除。俄罗斯方块+数独的混合体。",
    path: "/games/block-jigsaw",
    icon: "🧩",
    category: "puzzle",
    categoryName: "益智消除",
    color: "from-emerald-400 to-green-500",
    tags: ["方块", "拼图", "消除", "排行榜"],
    difficulty: "easy",
    avgSessionMin: 6,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 9,
  },

  /* --- 火柴人动作 (1款) --- */
  {
    id: "stickman-battle",
    name: "火柴人对战",
    description: "Stickman Hook风格火柴人格斗！控制火柴人攻击、闪避、连招，击败一波波敌人。Poki最火爆柴人类型。",
    path: "/games/stickman-battle",
    icon: "🥋",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-slate-500 to-gray-700",
    tags: ["火柴人", "格斗", "动作", "排行榜"],
    difficulty: "medium",
    avgSessionMin: 4,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },

  /* --- 模拟经营 (1款) --- */
  {
    id: "cafe-tycoon",
    name: "咖啡店大亨",
    description: "Monkey Mart风格模拟经营！接待顾客点单，制作咖啡赚取金币，升级店铺扩大规模。经营成长的快乐。",
    path: "/games/cafe-tycoon",
    icon: "☕",
    category: "simulation",
    categoryName: "模拟经营",
    color: "from-amber-600 to-yellow-700",
    tags: ["模拟", "经营", "咖啡店", "升级"],
    difficulty: "easy",
    avgSessionMin: 8,
    hasLeaderboard: false,
    hasDailyChallenge: false,
    retentionScore: 9,
  },

  /* --- 跑酷闯关 (1款) --- */
  {
    id: "ninja-runner",
    name: "忍者跑酷",
    description: "Obby风格跑酷闯关！控制忍者跳跃、滑铲、飞墙，躲避陷阱到达终点。10个关卡由易到难，每关不同玩法。",
    path: "/games/ninja-runner",
    icon: "🥷",
    category: "arcade",
    categoryName: "经典街机",
    color: "from-red-500 to-rose-600",
    tags: ["跑酷", "闯关", "忍者", "关卡"],
    difficulty: "medium",
    avgSessionMin: 5,
    hasLeaderboard: true,
    hasDailyChallenge: false,
    retentionScore: 8,
  },

  /* --- 螺丝/分类解谜 (1款) --- */
  {
    id: "bolt-sort",
    name: "螺丝分拣",
    description: "Screw Puzzle风格螺丝解谜！按正确顺序拧下螺丝，分类排列到正确位置。2026新兴解谜趋势，ASMR式解压。",
    path: "/games/bolt-sort",
    icon: "🔩",
    category: "brain",
    categoryName: "脑力训练",
    color: "from-zinc-400 to-slate-600",
    tags: ["螺丝", "分类", "解谜", "解压"],
    difficulty: "medium",
    avgSessionMin: 5,
    hasLeaderboard: false,
    hasDailyChallenge: true,
    retentionScore: 8,
  },
];

export function getGameById(id: string): Game | undefined {
  return games.find((g) => g.id === id);
}

export function getGamesByCategory(category: string): Game[] {
  return games.filter((g) => g.category === category);
}

export const gameCategories = [
  { id: "all", name: "全部游戏", icon: "🎮" },
  { id: "puzzle", name: "益智消除", icon: "🧩" },
  { id: "arcade", name: "经典街机", icon: "🕹️" },
  { id: "io", name: "竞技对抗", icon: "⚔️" },
  { id: "physics", name: "物理搞笑", icon: "🎲" },
  { id: "brain", name: "脑力训练", icon: "🧠" },
  { id: "daily", name: "每日挑战", icon: "📅" },
  { id: "reflex", name: "反应训练", icon: "⚡" },
  { id: "strategy", name: "策略对战", icon: "♟️" },
  { id: "casual", name: "休闲放置", icon: "🍃" },
  { id: "meme", name: "梗趣文化", icon: "🫧" },
  { id: "simulation", name: "模拟经营", icon: "🏪" },
];
