import {
  Braces,
  Binary,
  Link,
  Regex,
  Fingerprint,
  Clock,
  Palette,
  FileText,
  QrCode,
  KeyRound,
  Hash,
  Calculator,
  Home,
  Wallet,
  Scale,
  Baby,
  Ruler,
  Type,
  ArrowUpDown,
  Trash2,
  Shuffle,
  Ticket,
  Image,
  ImageDown,
  ImagePlus,
  FileImage,
  User,
  Droplets,
  Repeat,
  Timer,
  CalendarDays,
  Wallet as WalletIcon,
  FileDiff,
  Table2,
  Languages,
  Grid3X3,
  Code2,
  FileCode,
  ScanLine,
  AlignLeft,
  Contact,
  Crop,
  RotateCw,
  Maximize2,
  Sparkles,
  Layers,
  Grid2x2,
  Monitor,
  Smile,
  FileDown,
  Combine,
  Volume2,
  Eraser,
  Film,
  Circle,
  type LucideIcon,
} from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  path: string;
  icon: LucideIcon;
  category: string;
  color: string;
}

export const tools: Tool[] = [
  // 计算工具
  {
    id: "mortgage-calculator",
    name: "房贷计算器",
    description: "支持等额本息、等额本金，计算月供、总利息、还款总额",
    path: "/tools/mortgage-calculator",
    icon: Home,
    category: "计算工具",
    color: "from-rose-500 to-red-500",
  },
  {
    id: "tax-calculator",
    name: "个税计算器",
    description: "2026年最新个税计算，支持专项附加扣除和年终奖计算",
    path: "/tools/tax-calculator",
    icon: Wallet,
    category: "计算工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "bmi-calculator",
    name: "BMI计算器",
    description: "身体质量指数计算，评估体重健康状况，给出健康建议",
    path: "/tools/bmi-calculator",
    icon: Scale,
    category: "计算工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "age-calculator",
    name: "年龄计算器",
    description: "计算两个日期之间的年龄、天数、周数、月数",
    path: "/tools/age-calculator",
    icon: Baby,
    category: "计算工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "unit-converter",
    name: "单位换算器",
    description: "长度、重量、面积、体积、温度等多种单位换算",
    path: "/tools/unit-converter",
    icon: Ruler,
    category: "计算工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "base-converter",
    name: "进制转换",
    description: "二进制、八进制、十进制、十六进制互相转换",
    path: "/tools/base-converter",
    icon: Repeat,
    category: "计算工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "calculator",
    name: "科学计算器",
    description: "功能强大的科学计算器，支持复杂运算",
    path: "/tools/calculator",
    icon: Calculator,
    category: "计算工具",
    color: "from-cyan-500 to-blue-500",
  },

  // 文本工具
  {
    id: "word-counter",
    name: "字数统计",
    description: "统计字符数、字数、行数、段落数、中英文分开统计",
    path: "/tools/word-counter",
    icon: Type,
    category: "文本工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "case-converter",
    name: "大小写转换",
    description: "大写、小写、首字母大写、反转大小写、驼峰转换",
    path: "/tools/case-converter",
    icon: ArrowUpDown,
    category: "文本工具",
    color: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "text-dedup",
    name: "文字去重",
    description: "去除重复行、去除空白行、去除多余空格",
    path: "/tools/text-dedup",
    icon: Trash2,
    category: "文本工具",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "markdown",
    name: "Markdown 编辑器",
    description: "实时预览Markdown，支持导出HTML",
    path: "/tools/markdown",
    icon: FileText,
    category: "文本工具",
    color: "from-slate-500 to-gray-600",
  },
  {
    id: "amount-to-chinese",
    name: "金额大写转换",
    description: "数字金额转换为中文大写金额，支持整数小数，最大到万亿级别",
    path: "/tools/amount-to-chinese",
    icon: WalletIcon,
    category: "文本工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "text-diff",
    name: "文本对比工具",
    description: "在线对比两段文本的差异，支持逐字符和逐行对比，差异高亮显示",
    path: "/tools/text-diff",
    icon: FileDiff,
    category: "文本工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "traditional-simplified",
    name: "繁简转换",
    description: "简体中文和繁体中文互转，实时转换，常用字全覆盖",
    path: "/tools/traditional-simplified",
    icon: Languages,
    category: "文本工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "text-to-pinyin",
    name: "文字转拼音",
    description: "中文汉字转换为拼音，支持带声调、首字母模式，多种分隔符选择",
    path: "/tools/text-to-pinyin",
    icon: AlignLeft,
    category: "文本工具",
    color: "from-emerald-500 to-teal-500",
  },

  // 生成工具
  {
    id: "random-number",
    name: "随机数生成器",
    description: "生成指定范围的随机数，支持批量生成和去重",
    path: "/tools/random-number",
    icon: Shuffle,
    category: "生成工具",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "lucky-number",
    name: "幸运数字生成",
    description: "彩票号码、抽奖号码生成，支持自定义范围和数量",
    path: "/tools/lucky-number",
    icon: Ticket,
    category: "生成工具",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: "password-generator",
    name: "密码生成器",
    description: "生成安全的随机密码，可自定义强度和长度",
    path: "/tools/password-generator",
    icon: KeyRound,
    category: "生成工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "uuid-generator",
    name: "UUID 生成器",
    description: "一键生成UUID v1/v4，支持批量生成",
    path: "/tools/uuid-generator",
    icon: Fingerprint,
    category: "生成工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "qrcode",
    name: "二维码生成器",
    description: "生成自定义二维码，支持颜色和尺寸调整",
    path: "/tools/qrcode",
    icon: QrCode,
    category: "生成工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "qr-decoder",
    name: "二维码解码器",
    description: "从图片中解析二维码内容，支持上传和拖拽，快速识别二维码信息",
    path: "/tools/qr-decoder",
    icon: ScanLine,
    category: "生成工具",
    color: "from-cyan-500 to-teal-500",
  },

  // 转换工具
  {
    id: "image-to-base64",
    name: "图片转Base64",
    description: "上传图片转换为Base64编码，支持多种图片格式",
    path: "/tools/image-to-base64",
    icon: Image,
    category: "转换工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "base64",
    name: "Base64 编解码",
    description: "快速进行Base64编码和解码，支持文本和字符串",
    path: "/tools/base64",
    icon: Binary,
    category: "转换工具",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "color-picker",
    name: "颜色转换器",
    description: "HEX、RGB、HSL颜色格式互转，调色板工具",
    path: "/tools/color-picker",
    icon: Palette,
    category: "转换工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "url-encoder",
    name: "URL 编解码",
    description: "URL编码和解码工具，处理特殊字符转义",
    path: "/tools/url-encoder",
    icon: Link,
    category: "转换工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "pdf-compressor",
    name: "PDF压缩工具",
    description: "在线压缩PDF文件大小，支持多种压缩模式，本地处理安全可靠",
    path: "/tools/pdf-compressor",
    icon: FileDown,
    category: "转换工具",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "pdf-merge",
    name: "PDF合并工具",
    description: "将多个PDF文件合并为一个，支持拖拽排序，本地处理安全可靠",
    path: "/tools/pdf-merge",
    icon: Combine,
    category: "转换工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "video-to-gif",
    name: "视频转GIF",
    description: "将视频转换为GIF动图，支持截取片段、调整帧率和质量",
    path: "/tools/video-to-gif",
    icon: Film,
    category: "转换工具",
    color: "from-pink-500 to-rose-500",
  },

  // 生活工具
  {
    id: "countdown-timer",
    name: "倒计时/计时器",
    description: "在线倒计时和秒表功能，支持多组倒计时",
    path: "/tools/countdown-timer",
    icon: Timer,
    category: "生活工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "date-calculator",
    name: "日期计算器",
    description: "日期加减计算、计算两个日期之间的差值",
    path: "/tools/date-calculator",
    icon: CalendarDays,
    category: "生活工具",
    color: "from-lime-500 to-green-500",
  },
  {
    id: "timestamp",
    name: "时间戳转换",
    description: "Unix时间戳与日期时间格式互转",
    path: "/tools/timestamp",
    icon: Clock,
    category: "生活工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "text-to-speech",
    name: "文字转语音",
    description: "在线文字转语音朗读，支持多种音色、语速和音调调节",
    path: "/tools/text-to-speech",
    icon: Volume2,
    category: "生活工具",
    color: "from-orange-500 to-amber-500",
  },

  // 开发工具
  {
    id: "json-formatter",
    name: "JSON 格式化",
    description: "格式化、压缩、校验JSON数据，支持树状视图展示",
    path: "/tools/json-formatter",
    icon: Braces,
    category: "开发工具",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "css-formatter",
    name: "CSS 格式化/压缩",
    description: "CSS代码格式化和压缩工具，支持自定义缩进，一键美化和最小化CSS代码",
    path: "/tools/css-formatter",
    icon: Code2,
    category: "开发工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "html-formatter",
    name: "HTML 格式化/压缩",
    description: "HTML代码格式化和压缩工具，支持自定义缩进，一键美化和最小化HTML代码",
    path: "/tools/html-formatter",
    icon: FileCode,
    category: "开发工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "regex-tester",
    name: "正则表达式测试",
    description: "实时测试正则表达式，高亮匹配结果",
    path: "/tools/regex-tester",
    icon: Regex,
    category: "开发工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "hash-generator",
    name: "哈希生成器",
    description: "MD5、SHA-1、SHA-256等多种哈希算法",
    path: "/tools/hash-generator",
    icon: Hash,
    category: "开发工具",
    color: "from-violet-500 to-purple-500",
  },

  // 图片工具
  {
    id: "image-compressor",
    name: "图片压缩工具",
    description: "在线图片压缩，支持JPG/PNG/WebP，调整质量压缩后下载，节省存储空间",
    path: "/tools/image-compressor",
    icon: ImageDown,
    category: "图片工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "image-converter",
    name: "图片格式转换",
    description: "图片格式互转，支持JPG、PNG、WebP、BMP等多种格式，批量转换",
    path: "/tools/image-converter",
    icon: ImagePlus,
    category: "图片工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "image-to-pdf",
    name: "图片转PDF",
    description: "将图片转换为PDF文件，支持单图/多图合并PDF，调整页面大小",
    path: "/tools/image-to-pdf",
    icon: FileImage,
    category: "图片工具",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "avatar-generator",
    name: "头像生成器",
    description: "生成个性化头像，文字头像、渐变背景、多种配色方案，一键下载",
    path: "/tools/avatar-generator",
    icon: User,
    category: "图片工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "image-watermark",
    name: "图片加水印",
    description: "给图片添加文字或图片水印，支持位置选择、透明度调节、旋转",
    path: "/tools/image-watermark",
    icon: Droplets,
    category: "图片工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "image-crop",
    name: "图片裁剪工具",
    description: "在线图片裁剪，支持自由裁剪和固定比例裁剪，拖拽调整裁剪框，实时预览，一键下载",
    path: "/tools/image-crop",
    icon: Crop,
    category: "图片工具",
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "image-rotate",
    name: "图片旋转翻转",
    description: "在线图片旋转和翻转，支持任意角度旋转、水平垂直翻转，实时预览，一键下载",
    path: "/tools/image-rotate",
    icon: RotateCw,
    category: "图片工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "image-resize",
    name: "图片调整大小",
    description: "在线调整图片尺寸，支持像素和百分比缩放，锁定宽高比，多格式输出",
    path: "/tools/image-resize",
    icon: Maximize2,
    category: "图片工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "text-to-image",
    name: "文字转图片",
    description: "将文字转换为图片，自定义字体颜色背景，多种预设样式，社交媒体配图一键生成",
    path: "/tools/text-to-image",
    icon: Type,
    category: "图片工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "image-blur",
    name: "图片模糊像素化",
    description: "图片高斯模糊和马赛克像素化处理，支持强度调节和局部模糊，实时预览",
    path: "/tools/image-blur",
    icon: Sparkles,
    category: "图片工具",
    color: "from-slate-500 to-gray-600",
  },
  {
    id: "business-card",
    name: "名片生成器",
    description: "在线生成电子名片图片，多种模板风格，自定义配色，一键下载",
    path: "/tools/business-card",
    icon: Contact,
    category: "图片工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "image-grid",
    name: "图片拼接/长图",
    description: "多张图片横向纵向拼接，支持自定义间距、背景色、圆角，一键生成长图",
    path: "/tools/image-grid",
    icon: Layers,
    category: "图片工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "image-grid-cutter",
    name: "九宫格切图",
    description: "图片切成九宫格，支持多种网格和圆形裁剪，社交媒体发图必备",
    path: "/tools/image-grid-cutter",
    icon: Grid2x2,
    category: "图片工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "screenshot-maker",
    name: "截图美化",
    description: "给截图添加圆角、阴影、渐变背景和设备外壳，制作精美展示图",
    path: "/tools/screenshot-maker",
    icon: Monitor,
    category: "图片工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "meme-generator",
    name: "表情包生成器",
    description: "给图片加文字制作表情包，支持多种模板，自定义字体颜色描边",
    path: "/tools/meme-generator",
    icon: Smile,
    category: "图片工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "bg-remover",
    name: "图片抠图",
    description: "一键移除图片背景，支持多种抠图模式和边缘羽化，生成透明背景图",
    path: "/tools/bg-remover",
    icon: Eraser,
    category: "图片工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "circle-crop",
    name: "圆形头像裁剪",
    description: "将图片裁剪为圆形/圆角/六边形头像，支持边框美化，一键下载",
    path: "/tools/circle-crop",
    icon: Circle,
    category: "图片工具",
    color: "from-pink-500 to-rose-500",
  },
];

export const categories = [
  { id: "all", name: "全部工具", slug: "all", icon: Grid3X3 },
  { id: "计算工具", name: "计算工具", slug: "calculator", icon: Calculator },
  { id: "文本工具", name: "文本工具", slug: "text", icon: FileText },
  { id: "生成工具", name: "生成工具", slug: "generator", icon: Sparkles },
  { id: "转换工具", name: "转换工具", slug: "converter", icon: ArrowUpDown },
  { id: "图片工具", name: "图片工具", slug: "image", icon: Image },
  { id: "生活工具", name: "生活工具", slug: "life", icon: Home },
  { id: "开发工具", name: "开发工具", slug: "developer", icon: Code2 },
];

// Get category info by slug
export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug);
}

// Get category slug by name
export function getCategorySlugByName(name: string): string {
  const cat = categories.find((c) => c.name === name);
  return cat?.slug || "";
}

// Get all tools
export function getAllTools(): Tool[] {
  return tools;
}

// Get tools by category name
export function getToolsByCategory(categoryName: string): Tool[] {
  if (categoryName === "全部工具") return tools;
  return tools.filter((t) => t.category === categoryName);
}

// Get popular tools (first 8)
export function getPopularTools(): Tool[] {
  return tools.slice(0, 8);
}

// Get tool by slug/id
export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.id === slug);
}
