import {
  Braces,
  Binary,
  Link,
  Regex,
  Fingerprint,
  Clock,
  Palette,
  FileText,
  QrCode,
  KeyRound,
  Hash,
  Calculator,
  Home,
  Wallet,
  Scale,
  Baby,
  Ruler,
  Type,
  ArrowUpDown,
  Trash2,
  Shuffle,
  Ticket,
  Image,
  ImageDown,
  ImagePlus,
  FileImage,
  User,
  Droplets,
  Repeat,
  Timer,
  CalendarDays,
  Wallet as WalletIcon,
  FileDiff,
  Table2,
  Languages,
  Grid3X3,
  Code2,
  FileCode,
  ScanLine,
  AlignLeft,
  Contact,
  Crop,
  RotateCw,
  Maximize2,
  Sparkles,
  Layers,
  Grid2x2,
  Monitor,
  Smile,
  FileDown,
  Combine,
  Volume2,
  Eraser,
  Film,
  Circle,
  CheckCircle,
  ArrowLeftRight,
  Replace,
  Database,
  Minimize2,
  FileJson,
  ArrowRightLeft,
  Download,
  Trash,
  FlipHorizontal,
  FlipVertical,
  Sun,
  Square,
  Contrast,
  Minus,
  Lock,
  Unlock,
  Mail,
  Radio,
  Paintbrush,
  Wind,
  Box,
  Quote,
  AtSign,
  Zap,
  Users,
  Barcode,
  MessageSquare,
  Percent,
  DollarSign,
  TrendingUp,
  Flame,
  Target,
  Divide,
  Gauge,
  HardDrive,
  Activity,
  Beaker,
  Thermometer,
  Receipt,
  Banknote,
  PiggyBank,
  Coins,
  Heart,
  BadgePercent,
  FileSpreadsheet,

  FileType,
  FileKey,
  FileSignature,
  FileStack,
  FileOutput,
  FileInput,
  LayoutList,

  PenLine,
  Highlighter,
  Music,
  Video,
  VolumeX,
  FastForward,
  Rewind,
  AudioWaveform,
  Disc,
  Mic,
  Radio as RadioIcon,

  Timer as TimerIcon,

  Pause,
  RotateCcw,
  Coins as DiceIcon,
  Trophy,
  Target as TargetIcon,
  Globe,
  CheckSquare,
  ListTodo,
  Receipt as ReceiptIcon,
  Flame as FlameIcon,
  Droplet,
  Pipette,
  Blend,
  Sun as SunIcon,
  Circle as CircleIcon,
  Tag,
  Eye as EyeIcon,
  Type as TypeIcon,
  AlignCenter,
  ArrowDown,
  BarChart2,
  BookOpen,
  Check,
  Copy,
  Scissors,
  Play,
  FileSearch,
  GitCompare,
  ListOrdered,
  MoveHorizontal,


  Search,
  Sliders,
  Terminal,
  GitBranch,
  Star,
  Briefcase,
  Building2,
  Shield,
  Gift,
  Focus,
  Paintbrush2,
  Aperture,
  Wand2,
  CalendarClock,
  PawPrint,
  type LucideIcon,
} from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  path: string;
  icon: LucideIcon;
  category: string;
  color: string;
  tags?: string[];
}

export const tools: Tool[] = [
  // 计算工具
  {
    id: "mortgage-calculator",
    name: "房贷计算器",
    description: "支持等额本息、等额本金，计算月供、总利息、还款总额",
    path: "/tools/mortgage-calculator",
    icon: Home,
    category: "计算工具",
    color: "from-rose-500 to-red-500",
  },
  {
    id: "tax-calculator",
    name: "个税计算器",
    description: "2026年最新个税计算，支持专项附加扣除和年终奖计算",
    path: "/tools/tax-calculator",
    icon: Wallet,
    category: "计算工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "bmi-calculator",
    name: "BMI计算器",
    description: "身体质量指数计算，评估体重健康状况，给出健康建议",
    path: "/tools/bmi-calculator",
    icon: Scale,
    category: "计算工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "age-calculator",
    name: "年龄计算器",
    description: "计算两个日期之间的年龄、天数、周数、月数",
    path: "/tools/age-calculator",
    icon: Baby,
    category: "计算工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "unit-converter",
    name: "单位换算器",
    description: "长度、重量、面积、体积、温度等多种单位换算",
    path: "/tools/unit-converter",
    icon: Ruler,
    category: "计算工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "base-converter",
    name: "进制转换",
    description: "二进制、八进制、十进制、十六进制互相转换",
    path: "/tools/base-converter",
    icon: Repeat,
    category: "计算工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "calculator",
    name: "科学计算器",
    description: "功能强大的科学计算器，支持复杂运算",
    path: "/tools/calculator",
    icon: Calculator,
    category: "计算工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "compound-interest",
    name: "复利计算器",
    description: "计算复利收益，支持不同复利周期和投资期限",
    path: "/tools/compound-interest",
    icon: TrendingUp,
    category: "计算工具",
    color: "from-emerald-500 to-green-500",
  },
  {
    id: "simple-interest",
    name: "单利计算器",
    description: "快速计算单利利息、本息总额和到期收益",
    path: "/tools/simple-interest",
    icon: Coins,
    category: "计算工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "loan-calculator",
    name: "贷款计算器",
    description: "等额本息贷款计算，月供、总利息、还款总额一目了然",
    path: "/tools/loan-calculator",
    icon: PiggyBank,
    category: "计算工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "discount-calculator",
    name: "折扣计算器",
    description: "计算折扣后价格、节省金额，支持多件折扣和满减",
    path: "/tools/discount-calculator",
    icon: BadgePercent,
    category: "计算工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "percentage-calculator",
    name: "百分比计算器",
    description: "支持多种百分比计算，增减百分比、比例换算",
    path: "/tools/percentage-calculator",
    icon: Percent,
    category: "计算工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "percentage-change",
    name: "百分比变化计算器",
    description: "计算两个数值之间的百分比增减变化率",
    path: "/tools/percentage-change",
    icon: TrendingUp,
    category: "计算工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "vat-calculator",
    name: "增值税计算器",
    description: "计算含税价、不含税价和增值税额",
    path: "/tools/vat-calculator",
    icon: Receipt,
    category: "计算工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "tip-calculator",
    name: "小费计算器",
    description: "快速计算小费金额和人均分摊费用",
    path: "/tools/tip-calculator",
    icon: Banknote,
    category: "计算工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "roi-calculator",
    name: "投资回报率计算器",
    description: "计算投资回报率(ROI)、年化收益率和投资回收期",
    path: "/tools/roi-calculator",
    icon: TrendingUp,
    category: "计算工具",
    color: "from-indigo-500 to-violet-500",
  },
  {
    id: "salary-calculator",
    name: "税前税后工资计算器",
    description: "计算五险一金、个税及税后实发工资",
    path: "/tools/salary-calculator",
    icon: Wallet,
    category: "计算工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "bmr-calculator",
    name: "基础代谢率计算器",
    description: "BMR计算，了解每日静息消耗热量",
    path: "/tools/bmr-calculator",
    icon: Flame,
    category: "计算工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "calorie-calculator",
    name: "卡路里计算器",
    description: "根据活动水平计算每日热量需求和目标摄入",
    path: "/tools/calorie-calculator",
    icon: Activity,
    category: "计算工具",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "body-fat-calculator",
    name: "体脂率计算器",
    description: "美国海军公式计算体脂率和瘦体重",
    path: "/tools/body-fat-calculator",
    icon: Heart,
    category: "计算工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "ideal-weight",
    name: "理想体重计算器",
    description: "多种科学公式计算理想体重范围",
    path: "/tools/ideal-weight",
    icon: Target,
    category: "计算工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "length-converter",
    name: "长度单位换算",
    description: "米、千米、厘米、英寸、英尺、英里等长度单位换算",
    path: "/tools/length-converter",
    icon: Ruler,
    category: "计算工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "weight-converter",
    name: "重量单位换算",
    description: "千克、克、磅、盎司、斤、两等重量单位换算",
    path: "/tools/weight-converter",
    icon: Scale,
    category: "计算工具",
    color: "from-emerald-500 to-green-500",
  },
  {
    id: "temperature-converter",
    name: "温度换算",
    description: "摄氏度、华氏度、开尔文、兰氏度等温度单位换算",
    path: "/tools/temperature-converter",
    icon: Thermometer,
    category: "计算工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "area-converter",
    name: "面积单位换算",
    description: "平方米、公顷、亩、平方英尺、英亩等面积单位换算",
    path: "/tools/area-converter",
    icon: Grid3X3,
    category: "计算工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "volume-converter",
    name: "体积单位换算",
    description: "升、毫升、立方米、加仑、夸脱等体积单位换算",
    path: "/tools/volume-converter",
    icon: Beaker,
    category: "计算工具",
    color: "from-cyan-500 to-teal-500",
  },
  {
    id: "speed-converter",
    name: "速度单位换算",
    description: "米/秒、千米/时、英里/时、节、马赫等速度单位换算",
    path: "/tools/speed-converter",
    icon: Gauge,
    category: "计算工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "data-size-converter",
    name: "数据容量换算",
    description: "字节、KB、MB、GB、TB、PB等数据存储单位换算",
    path: "/tools/data-size-converter",
    icon: HardDrive,
    category: "计算工具",
    color: "from-blue-600 to-indigo-600",
  },
  {
    id: "time-converter",
    name: "时间单位换算",
    description: "秒、分钟、小时、天、周、月、年等时间单位换算",
    path: "/tools/time-converter",
    icon: Clock,
    category: "计算工具",
    color: "from-rose-500 to-red-500",
  },
  {
    id: "scientific-calculator",
    name: "科学计算器",
    description: "三角函数、对数、指数、阶乘等科学计算功能",
    path: "/tools/scientific-calculator",
    icon: Calculator,
    category: "计算工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "fraction-calculator",
    name: "分数计算器",
    description: "分数加减乘除运算，自动约分，显示最简分数",
    path: "/tools/fraction-calculator",
    icon: Divide,
    category: "计算工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "gcd-lcm-calculator",
    name: "最大公约数/最小公倍数",
    description: "GCD和LCM计算，支持多位数，展示质因数分解",
    path: "/tools/gcd-lcm-calculator",
    icon: Hash,
    category: "计算工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "overtime-pay-calculator",
    name: "加班工资计算器",
    description: "计算工作日、周末、法定节假日加班工资，支持倍速设置，一键算出加班费",
    path: "/tools/overtime-pay-calculator",
    icon: Briefcase,
    category: "计算工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "housing-fund-calculator",
    name: "公积金计算器",
    description: "计算住房公积金缴存额度和贷款额度，支持不同城市和缴存比例",
    path: "/tools/housing-fund-calculator",
    icon: Building2,
    category: "计算工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "social-insurance-calculator",
    name: "社保计算器",
    description: "计算五险一金缴纳明细，养老、医疗、失业、工伤、生育保险明细一览",
    path: "/tools/social-insurance-calculator",
    icon: Shield,
    category: "计算工具",
    color: "from-emerald-500 to-teal-500",
  },

  // 文本工具
  {
    id: "word-counter",
    name: "字数统计",
    description: "统计字符数、字数、行数、段落数、中英文分开统计",
    path: "/tools/word-counter",
    icon: Type,
    category: "文本工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "case-converter",
    name: "大小写转换",
    description: "大写、小写、首字母大写、反转大小写、驼峰转换",
    path: "/tools/case-converter",
    icon: ArrowUpDown,
    category: "文本工具",
    color: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "text-dedup",
    name: "文字去重",
    description: "去除重复行、去除空白行、去除多余空格",
    path: "/tools/text-dedup",
    icon: Trash2,
    category: "文本工具",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "markdown",
    name: "Markdown 编辑器",
    description: "实时预览Markdown，支持导出HTML",
    path: "/tools/markdown",
    icon: FileText,
    category: "文本工具",
    color: "from-slate-500 to-gray-600",
  },
  {
    id: "amount-to-chinese",
    name: "金额大写转换",
    description: "数字金额转换为中文大写金额，支持整数小数，最大到万亿级别",
    path: "/tools/amount-to-chinese",
    icon: WalletIcon,
    category: "文本工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "text-diff",
    name: "文本对比工具",
    description: "在线对比两段文本的差异，支持逐字符和逐行对比，差异高亮显示",
    path: "/tools/text-diff",
    icon: FileDiff,
    category: "文本工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "traditional-simplified",
    name: "繁简转换",
    description: "简体中文和繁体中文互转，实时转换，常用字全覆盖",
    path: "/tools/traditional-simplified",
    icon: Languages,
    category: "文本工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "text-to-pinyin",
    name: "文字转拼音",
    description: "中文汉字转换为拼音，支持带声调、首字母模式，多种分隔符选择",
    path: "/tools/text-to-pinyin",
    icon: AlignLeft,
    category: "文本工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "title-case",
    name: "标题大小写转换",
    description: "将文本转换为标题格式，每个单词首字母大写，其余字母小写",
    path: "/tools/title-case",
    icon: Type,
    category: "文本工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "sentence-case",
    name: "句子首字母大写",
    description: "将文本转换为句子格式，每句首字母大写，其余字母小写",
    path: "/tools/sentence-case",
    icon: AlignLeft,
    category: "文本工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "toggle-case",
    name: "大小写反转",
    description: "反转文本中每个字母的大小写，大写变小写，小写变大写",
    path: "/tools/toggle-case",
    icon: ArrowUpDown,
    category: "文本工具",
    color: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "capitalize-case",
    name: "单词首字母大写",
    description: "将文本中每个单词的首字母转换为大写，其余字母保持不变",
    path: "/tools/capitalize-case",
    icon: Type,
    category: "文本工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "camel-case",
    name: "驼峰命名转换",
    description: "将文本转换为驼峰命名格式，常用于编程变量名和函数名",
    path: "/tools/camel-case",
    icon: Braces,
    category: "文本工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "snake-case",
    name: "下划线命名转换",
    description: "将文本转换为下划线命名格式，单词之间用下划线连接",
    path: "/tools/snake-case",
    icon: Minimize2,
    category: "文本工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "kebab-case",
    name: "短横线命名转换",
    description: "将文本转换为短横线命名格式，单词之间用短横线连接",
    path: "/tools/kebab-case",
    icon: Minus,
    category: "文本工具",
    color: "from-rose-500 to-red-500",
  },
  {
    id: "remove-duplicate-lines",
    name: "去除重复行",
    description: "一键去除文本中的重复行，支持忽略大小写和保留首次出现",
    path: "/tools/remove-duplicate-lines",
    icon: Trash2,
    category: "文本工具",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "remove-line-breaks",
    name: "去除换行符",
    description: "去除文本中的换行符，将多行文本合并为一行，支持自定义分隔符",
    path: "/tools/remove-line-breaks",
    icon: AlignLeft,
    category: "文本工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "remove-html-tags",
    name: "去除HTML标签",
    description: "一键去除文本中的所有HTML标签，提取纯文本内容",
    path: "/tools/remove-html-tags",
    icon: Code2,
    category: "文本工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "extract-emails",
    name: "提取邮箱地址",
    description: "从文本中提取所有邮箱地址，支持去重和导出，快速收集邮箱列表",
    path: "/tools/extract-emails",
    icon: Mail,
    category: "文本工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "extract-urls",
    name: "提取URL链接",
    description: "从文本中提取所有URL链接，支持去重和导出，快速收集网址列表",
    path: "/tools/extract-urls",
    icon: Link,
    category: "文本工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "extract-numbers",
    name: "提取数字",
    description: "从文本中提取所有数字，支持整数、小数和负数，快速提取数值数据",
    path: "/tools/extract-numbers",
    icon: Hash,
    category: "文本工具",
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "character-count",
    name: "字符数统计",
    description: "统计文本的字符数量，支持含空格和不含空格两种统计方式",
    path: "/tools/character-count",
    icon: Type,
    category: "文本工具",
    color: "from-sky-500 to-cyan-500",
  },
  {
    id: "word-count",
    name: "词数统计",
    description: "统计文本中的单词数量，支持中英文混合统计，实时计算",
    path: "/tools/word-count",
    icon: FileText,
    category: "文本工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "line-count",
    name: "行数统计",
    description: "统计文本的行数，支持统计非空行数和总行数，实时计算",
    path: "/tools/line-count",
    icon: AlignLeft,
    category: "文本工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "paragraph-count",
    name: "段落数统计",
    description: "统计文本中的段落数量，自动识别空行分隔的段落，实时计算",
    path: "/tools/paragraph-count",
    icon: FileText,
    category: "文本工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "sentence-count",
    name: "句子数统计",
    description: "统计文本中的句子数量，支持中英文标点识别，实时计算",
    path: "/tools/sentence-count",
    icon: AlignLeft,
    category: "文本工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "reading-time",
    name: "阅读时间估算",
    description: "估算阅读文本所需的时间，支持自定义阅读速度，中英文自适应",
    path: "/tools/reading-time",
    icon: Clock,
    category: "文本工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "text-encrypt",
    name: "文本加密工具",
    description: "多种文本加密方式，支持Base64、URL编码等常用加密算法",
    path: "/tools/text-encrypt",
    icon: Lock,
    category: "文本工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "text-decrypt",
    name: "文本解密工具",
    description: "多种文本解密方式，支持Base64、URL编码等常用解密算法",
    path: "/tools/text-decrypt",
    icon: Unlock,
    category: "文本工具",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "caesar-cipher",
    name: "凯撒密码",
    description: "经典凯撒密码加密解密，支持自定义位移量，加密解密一键切换",
    path: "/tools/caesar-cipher",
    icon: KeyRound,
    category: "文本工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "morse-code",
    name: "摩斯电码转换",
    description: "摩斯电码编码和解码，支持中英文，一键转换，支持自定义间隔",
    path: "/tools/morse-code",
    icon: Radio,
    category: "文本工具",
    color: "from-slate-500 to-gray-600",
  },
  {
    id: "leet-speak",
    name: "火星文/Leet语转换",
    description: "将普通文本转换为Leet语/火星文，支持多种替换风格，趣味文字转换",
    path: "/tools/leet-speak",
    icon: Sparkles,
    category: "文本工具",
    color: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "character-frequency",
    name: "字符频率统计",
    description: "统计文本中每个字符出现的频率，按出现次数排序，快速分析字符分布",
    path: "/tools/character-frequency",
    icon: BarChart2,
    category: "文本工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "word-frequency",
    name: "词频统计",
    description: "统计文本中单词/词语的出现频率，按次数排序，分析文本关键词分布",
    path: "/tools/word-frequency",
    icon: BarChart2,
    category: "文本工具",
    color: "from-indigo-500 to-violet-500",
  },
  {
    id: "text-shuffle",
    name: "文本打乱顺序",
    description: "随机打乱文本中的字符、单词或行的顺序，支持多种打乱模式",
    path: "/tools/text-shuffle",
    icon: Shuffle,
    category: "文本工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "letter-spacing",
    name: "字间距生成器",
    description: "在文本字符之间添加空格或自定义字符，生成带间距的文字效果",
    path: "/tools/letter-spacing",
    icon: MoveHorizontal,
    category: "文本工具",
    color: "from-cyan-500 to-teal-500",
  },
  {
    id: "upside-down-text",
    name: "倒字/翻转文字",
    description: "将文字上下颠倒翻转，生成倒字效果，趣味文字转换工具",
    path: "/tools/upside-down-text",
    icon: FlipVertical,
    category: "文本工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "zalgo-text",
    name: "Zalgo文字生成",
    description: "生成Zalgo/乱码文字效果，自定义恐怖风格文字，社交媒体创意文字",
    path: "/tools/zalgo-text",
    icon: Sparkles,
    category: "文本工具",
    color: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "text-to-emoji",
    name: "文字转emoji",
    description: "将文字转换为emoji表情，支持多种emoji风格，趣味文字转换",
    path: "/tools/text-to-emoji",
    icon: Smile,
    category: "文本工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "emoji-to-text",
    name: "emoji转文字",
    description: "将emoji表情转换为文字描述，解析emoji含义，快速了解emoji转文字",
    path: "/tools/emoji-to-text",
    icon: Smile,
    category: "文本工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "accent-remover",
    name: "去除重音符号",
    description: "去除文字中的重音符号和变音符号，将带重音的字符转换为普通字符",
    path: "/tools/accent-remover",
    icon: Eraser,
    category: "文本工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "text-truncator",
    name: "文本截断工具",
    description: "按字符数或字数截断文本，支持添加省略号，多种截断模式",
    path: "/tools/text-truncator",
    icon: Scissors,
    category: "文本工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "text-padder",
    name: "文本填充对齐",
    description: "在文本前后填充字符使文本对齐，支持左对齐、右对齐、居中对齐",
    path: "/tools/text-padder",
    icon: AlignCenter,
    category: "文本工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "line-numbering",
    name: "文本加行号",
    description: "为文本每行添加行号，支持自定义行号格式和起始行号",
    path: "/tools/line-numbering",
    icon: ListOrdered,
    category: "文本工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "duplicate-finder",
    name: "重复内容查找",
    description: "查找文本中的重复行、重复单词，高亮显示重复内容，支持去重",
    path: "/tools/duplicate-finder",
    icon: Copy,
    category: "文本工具",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "text-analyzer",
    name: "文本综合分析",
    description: "文本综合分析工具，统计字符、词频、可读性、平均词长等多维度分析",
    path: "/tools/text-analyzer",
    icon: FileSearch,
    category: "文本工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "keyword-extractor",
    name: "关键词提取",
    description: "从文本中自动提取关键词和高频词汇，支持中英文，快速获取文章核心词汇",
    path: "/tools/keyword-extractor",
    icon: KeyRound,
    category: "文本工具",
    color: "from-amber-500 to-orange-500",
  },

  // 生成工具
  {
    id: "random-number",
    name: "随机数生成器",
    description: "生成指定范围的随机数，支持批量生成和去重",
    path: "/tools/random-number",
    icon: Shuffle,
    category: "生成工具",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "lucky-number",
    name: "幸运数字生成",
    description: "彩票号码、抽奖号码生成，支持自定义范围和数量",
    path: "/tools/lucky-number",
    icon: Ticket,
    category: "生成工具",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: "password-generator",
    name: "密码生成器",
    description: "生成安全的随机密码，可自定义强度和长度",
    path: "/tools/password-generator",
    icon: KeyRound,
    category: "生成工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "uuid-generator",
    name: "UUID 生成器",
    description: "一键生成UUID v1/v4，支持批量生成",
    path: "/tools/uuid-generator",
    icon: Fingerprint,
    category: "生成工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "qrcode",
    name: "二维码生成器",
    description: "生成自定义二维码，支持颜色和尺寸调整",
    path: "/tools/qrcode",
    icon: QrCode,
    category: "生成工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "qr-decoder",
    name: "二维码解码器",
    description: "从图片中解析二维码内容，支持上传和拖拽，快速识别二维码信息",
    path: "/tools/qr-decoder",
    icon: ScanLine,
    category: "生成工具",
    color: "from-cyan-500 to-teal-500",
  },
  {
    id: "color-palette-generator",
    name: "调色板生成器",
    description: "随机生成5色配色方案，支持多种配色风格，一键复制颜色代码",
    path: "/tools/color-palette-generator",
    icon: Palette,
    category: "生成工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "gradient-generator",
    name: "渐变生成器",
    description: "在线生成CSS渐变背景，支持线性、径向渐变，实时预览和代码复制",
    path: "/tools/gradient-generator",
    icon: Paintbrush,
    category: "生成工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "random-color",
    name: "随机颜色生成器",
    description: "一键生成随机颜色，支持HEX、RGB、HSL格式，快速获取配色灵感",
    path: "/tools/random-color",
    icon: Sparkles,
    category: "生成工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "color-contrast-checker",
    name: "颜色对比度检测",
    description: "检测两种颜色的对比度是否符合WCAG标准，确保文字可读性",
    path: "/tools/color-contrast-checker",
    icon: Contrast,
    category: "生成工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "tailwind-gradient",
    name: "Tailwind渐变生成器",
    description: "生成Tailwind CSS渐变类名，支持多种渐变方向和颜色组合",
    path: "/tools/tailwind-gradient",
    icon: Wind,
    category: "生成工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "shadow-generator",
    name: "CSS阴影生成器",
    description: "可视化生成CSS box-shadow代码，支持多层阴影、内阴影、模糊和扩散调整",
    path: "/tools/shadow-generator",
    icon: Box,
    category: "生成工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "css-gradient-generator",
    name: "CSS渐变生成",
    description: "专业CSS渐变生成器，支持多色点、角度调整、线性和径向渐变",
    path: "/tools/css-gradient-generator",
    icon: Droplets,
    category: "生成工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "css-box-shadow",
    name: "CSS阴影生成",
    description: "快速生成CSS box-shadow代码，自定义偏移、模糊、扩散和颜色",
    path: "/tools/css-box-shadow",
    icon: Square,
    category: "生成工具",
    color: "from-slate-500 to-gray-600",
  },
  {
    id: "css-border-radius",
    name: "CSS圆角生成器",
    description: "可视化生成CSS border-radius代码，支持八个角分别调整",
    path: "/tools/css-border-radius",
    icon: Circle,
    category: "生成工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "css-grid-generator",
    name: "CSS Grid布局生成器",
    description: "可视化生成CSS Grid布局代码，自定义行列数、间距和对齐方式",
    path: "/tools/css-grid-generator",
    icon: Grid3X3,
    category: "生成工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "css-flex-generator",
    name: "CSS Flexbox生成器",
    description: "可视化生成CSS Flexbox布局代码，灵活调整方向、对齐和换行",
    path: "/tools/css-flex-generator",
    icon: AlignLeft,
    category: "生成工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "html-table-generator",
    name: "HTML表格生成器",
    description: "在线生成HTML表格代码，自定义行列数、边框、表头和样式",
    path: "/tools/html-table-generator",
    icon: Table2,
    category: "生成工具",
    color: "from-emerald-500 to-green-500",
  },
  {
    id: "meta-tag-generator",
    name: "Meta标签生成器",
    description: "生成SEO优化的Meta标签，包括标题、描述、OG标签、Twitter卡片等",
    path: "/tools/meta-tag-generator",
    icon: Code2,
    category: "生成工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "robots-txt-generator",
    name: "robots.txt生成器",
    description: "在线生成robots.txt文件，自定义搜索引擎爬取规则和sitemap路径",
    path: "/tools/robots-txt-generator",
    icon: FileCode,
    category: "生成工具",
    color: "from-gray-500 to-slate-600",
  },
  {
    id: "random-quote-generator",
    name: "随机名言生成器",
    description: "随机生成名人名言、励志语录，中英文双语，每日灵感来源",
    path: "/tools/random-quote-generator",
    icon: Quote,
    category: "生成工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "random-name-generator",
    name: "随机姓名生成器",
    description: "随机生成中文名和英文名，支持性别选择，批量生成姓名列表",
    path: "/tools/random-name-generator",
    icon: User,
    category: "生成工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "username-generator",
    name: "用户名生成器",
    description: "在线生成各种风格的用户名/网名，霸气、可爱、文艺、英文等多种风格",
    path: "/tools/username-generator",
    icon: AtSign,
    category: "生成工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "catchphrase-generator",
    name: "口号标语生成器",
    description: "随机生成创意口号和标语，适用于品牌、活动、产品宣传",
    path: "/tools/catchphrase-generator",
    icon: Zap,
    category: "生成工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "team-picker",
    name: "随机分组工具",
    description: "随机分组/分队工具，支持按人数或组数分配，公平随机分组",
    path: "/tools/team-picker",
    icon: Users,
    category: "生成工具",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "placeholder-text-generator",
    name: "占位符文本生成器",
    description: "生成各种占位符文本，支持自定义长度、格式和语言，用于设计原型填充",
    path: "/tools/placeholder-text-generator",
    icon: Wand2,
    category: "生成工具",
    color: "from-pink-500 to-rose-500",
  },

  // 转换工具
  {
    id: "image-to-base64",
    name: "图片转Base64",
    description: "上传图片转换为Base64编码，支持多种图片格式",
    path: "/tools/image-to-base64",
    icon: Image,
    category: "转换工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "base64",
    name: "Base64 编解码",
    description: "快速进行Base64编码和解码，支持文本和字符串",
    path: "/tools/base64",
    icon: Binary,
    category: "转换工具",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "color-picker",
    name: "颜色转换器",
    description: "HEX、RGB、HSL颜色格式互转，调色板工具",
    path: "/tools/color-picker",
    icon: Palette,
    category: "转换工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "url-encoder",
    name: "URL 编解码",
    description: "URL编码和解码工具，处理特殊字符转义",
    path: "/tools/url-encoder",
    icon: Link,
    category: "转换工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "pdf-compressor",
    name: "PDF压缩工具",
    description: "在线压缩PDF文件大小，支持多种压缩模式，本地处理安全可靠",
    path: "/tools/pdf-compressor",
    icon: FileDown,
    category: "转换工具",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "pdf-merge",
    name: "PDF合并工具",
    description: "将多个PDF文件合并为一个，支持拖拽排序，本地处理安全可靠",
    path: "/tools/pdf-merge",
    icon: Combine,
    category: "转换工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "video-to-gif",
    name: "视频转GIF",
    description: "将视频转换为GIF动图，支持截取片段、调整帧率和质量",
    path: "/tools/video-to-gif",
    icon: Film,
    category: "转换工具",
    color: "from-pink-500 to-rose-500",
  },

  // 生活工具
  {
    id: "countdown-timer",
    name: "倒计时/计时器",
    description: "在线倒计时和秒表功能，支持多组倒计时",
    path: "/tools/countdown-timer",
    icon: Timer,
    category: "生活工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "date-calculator",
    name: "日期计算器",
    description: "日期加减计算、计算两个日期之间的差值",
    path: "/tools/date-calculator",
    icon: CalendarDays,
    category: "生活工具",
    color: "from-lime-500 to-green-500",
  },
  {
    id: "timestamp",
    name: "时间戳转换",
    description: "Unix时间戳与日期时间格式互转",
    path: "/tools/timestamp",
    icon: Clock,
    category: "生活工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "text-to-speech",
    name: "文字转语音",
    description: "在线文字转语音朗读，支持多种音色、语速和音调调节",
    path: "/tools/text-to-speech",
    icon: Volume2,
    category: "生活工具",
    color: "from-orange-500 to-amber-500",
  },

  {
    id: "pomodoro-timer",
    name: "番茄钟计时器",
    description: "专注工作25分钟休息5分钟，提高效率的番茄工作法计时器",
    path: "/tools/pomodoro-timer",
    icon: TimerIcon,
    category: "生活工具",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "stopwatch",
    name: "秒表计时器",
    description: "精确毫秒级秒表，支持计次记录，多段计时",
    path: "/tools/stopwatch",
    icon: Play,
    category: "生活工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "flip-coin",
    name: "抛硬币",
    description: "在线抛硬币，随机决定正反面，帮你快速做决定",
    path: "/tools/flip-coin",
    icon: Coins,
    category: "生活工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "roll-dice",
    name: "掷骰子",
    description: "在线掷骰子，支持多个骰子和自定义面数，桌游必备",
    path: "/tools/roll-dice",
    icon: DiceIcon,
    category: "生活工具",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "random-picker",
    name: "随机选择器",
    description: "输入多个选项随机抽取，帮你快速做决定，支持抽取多个",
    path: "/tools/random-picker",
    icon: Shuffle,
    category: "生活工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "wheel-spinner",
    name: "转盘抽奖",
    description: "自定义选项的转盘抽奖工具，公平随机，视觉效果炫酷",
    path: "/tools/wheel-spinner",
    icon: Circle,
    category: "生活工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "lucky-draw",
    name: "抽奖/抽签工具",
    description: "自定义奖品和概率的抽奖工具，支持一、二、三等奖设置",
    path: "/tools/lucky-draw",
    icon: Trophy,
    category: "生活工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "days-between",
    name: "日期差计算器",
    description: "计算两个日期之间相差的天数、周数、月数、年数",
    path: "/tools/days-between",
    icon: CalendarDays,
    category: "生活工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "world-clock",
    name: "世界时钟",
    description: "查看全球各城市当前时间，多时区对比，支持添加自定义城市",
    path: "/tools/world-clock",
    icon: Globe,
    category: "生活工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "habit-tracker",
    name: "习惯打卡",
    description: "每日习惯打卡追踪，养成好习惯，可视化打卡记录",
    path: "/tools/habit-tracker",
    icon: CheckSquare,
    category: "生活工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "todo-list",
    name: "待办事项",
    description: "简洁的待办事项清单，分类管理，标记完成，本地存储",
    path: "/tools/todo-list",
    icon: ListTodo,
    category: "生活工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "expense-tracker",
    name: "记账本",
    description: "简单的收支记账工具，分类统计，月度收支一目了然",
    path: "/tools/expense-tracker",
    icon: ReceiptIcon,
    category: "生活工具",
    color: "from-emerald-500 to-green-500",
  },
  {
    id: "calorie-tracker",
    name: "卡路里记录",
    description: "记录每日饮食摄入热量，常见食物热量查询，健康饮食管理",
    path: "/tools/calorie-tracker",
    icon: FlameIcon,
    category: "生活工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "water-tracker",
    name: "喝水打卡提醒",
    description: "每日喝水打卡，记录饮水量，设置喝水目标和提醒",
    path: "/tools/water-tracker",
    icon: Droplet,
    category: "生活工具",
    color: "from-cyan-500 to-teal-500",
  },
  {
    id: "work-hours-calculator",
    name: "工时计算器",
    description: "计算上下班工时，支持午休扣除、加班计算，一键算出每日/每周/每月工作时长",
    path: "/tools/work-hours-calculator",
    icon: Briefcase,
    category: "生活工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "due-date-calculator",
    name: "预产期计算器",
    description: "根据末次月经日期计算预产期，同时显示孕周、胎儿发育阶段和重要产检时间",
    path: "/tools/due-date-calculator",
    icon: Baby,
    category: "生活工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "blood-type-calculator",
    name: "血型遗传计算器",
    description: "根据父母血型推算子女可能的血型，A型B型O型AB型遗传规律一目了然",
    path: "/tools/blood-type-calculator",
    icon: Droplet,
    category: "生活工具",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "zodiac-sign",
    name: "星座查询",
    description: "根据出生日期查询星座，查看星座性格特点、配对指数和运势简介",
    path: "/tools/zodiac-sign",
    icon: Star,
    category: "生活工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "chinese-zodiac",
    name: "生肖查询",
    description: "根据出生年份查询生肖属相，查看生肖性格特点、年份对照表和运势",
    path: "/tools/chinese-zodiac",
    icon: PawPrint,
    category: "生活工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "anniversary-calculator",
    name: "纪念日计算器",
    description: "计算重要纪念日天数，支持恋爱纪念日、结婚纪念日、生日倒计时提醒",
    path: "/tools/anniversary-calculator",
    icon: Heart,
    category: "生活工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "holiday-finder",
    name: "节日查询",
    description: "全年节日查询，法定节假日、传统节日、国际节日大全，支持按月份查看",
    path: "/tools/holiday-finder",
    icon: Gift,
    category: "生活工具",
    color: "from-emerald-500 to-green-500",
  },
  {
    id: "safe-period-calculator",
    name: "安全期计算器",
    description: "女性安全期计算器，根据月经周期计算安全期、排卵期和易孕期",
    path: "/tools/safe-period-calculator",
    icon: CalendarDays,
    category: "生活工具",
    color: "from-pink-500 to-fuchsia-500",
  },
  {
    id: "baby-height-prediction",
    name: "宝宝身高预测",
    description: "根据父母身高预测宝宝未来身高，支持男孩女孩分别预测，给出身高范围",
    path: "/tools/baby-height-prediction",
    icon: Ruler,
    category: "生活工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "currency-converter",
    name: "汇率换算",
    description: "常用货币汇率换算工具，支持美元、欧元、日元等主流货币实时汇率转换",
    path: "/tools/currency-converter",
    icon: DollarSign,
    category: "生活工具",
    color: "from-green-500 to-emerald-500",
  },

  // 设计工具
  {
    id: "color-palette-from-image",
    name: "图片取色/提取配色",
    description: "上传图片自动提取主色调和配色方案，智能提取多种颜色",
    path: "/tools/color-palette-from-image",
    icon: Pipette,
    category: "设计工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "tailwind-palette",
    name: "Tailwind调色板生成",
    description: "从基础色生成Tailwind风格的11级色阶，用于UI设计系统",
    path: "/tools/tailwind-palette",
    icon: Palette,
    category: "设计工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "color-mixer",
    name: "颜色混合器",
    description: "混合两种颜色生成渐变色阶，自定义混合步数，获取过渡色",
    path: "/tools/color-mixer",
    icon: Blend,
    category: "设计工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "color-shades-generator",
    name: "颜色明度渐变生成",
    description: "从基础色生成不同明度的色阶，用于UI设计的颜色系统",
    path: "/tools/color-shades-generator",
    icon: SunIcon,
    category: "设计工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "color-wheel",
    name: "色轮/色环",
    description: "交互式色轮工具，点击选择颜色，查看互补色、类似色、三色配色",
    path: "/tools/color-wheel",
    icon: CircleIcon,
    category: "设计工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "color-namer",
    name: "颜色命名工具",
    description: "输入颜色代码获取颜色名称，帮助设计师快速识别和命名颜色",
    path: "/tools/color-namer",
    icon: Tag,
    category: "设计工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "rgb-to-hsl",
    name: "RGB转HSL",
    description: "快速将RGB颜色转换为HSL色彩空间，可视化色相、饱和度、亮度",
    path: "/tools/rgb-to-hsl",
    icon: ArrowRightLeft,
    category: "设计工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "color-blind-simulator",
    name: "色盲模拟器",
    description: "模拟不同类型色盲用户看到的效果，帮助创建更具包容性的设计",
    path: "/tools/color-blind-simulator",
    icon: EyeIcon,
    category: "设计工具",
    color: "from-cyan-500 to-teal-500",
  },
  {
    id: "gradient-text-generator",
    name: "渐变文字生成器",
    description: "创建炫酷的渐变文字效果，自定义颜色角度样式，一键复制CSS代码",
    path: "/tools/gradient-text-generator",
    icon: TypeIcon,
    category: "设计工具",
    color: "from-fuchsia-500 to-purple-500",
  },

  // 开发工具
  {
    id: "json-formatter",
    name: "JSON 格式化",
    description: "格式化、压缩、校验JSON数据，支持树状视图展示",
    path: "/tools/json-formatter",
    icon: Braces,
    category: "开发工具",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "json-to-yaml",
    name: "JSON 转 YAML",
    description: "快速将 JSON 数据转换为 YAML 格式，数据本地处理安全可靠",
    path: "/tools/json-to-yaml",
    icon: FileJson,
    category: "开发工具",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "yaml-to-json",
    name: "YAML 转 JSON",
    description: "快速将 YAML 配置转换为 JSON 格式，数据本地处理安全可靠",
    path: "/tools/yaml-to-json",
    icon: FileText,
    category: "开发工具",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "json-to-csv",
    name: "JSON 转 CSV",
    description: "快速将 JSON 数组转换为 CSV 表格格式，支持自定义分隔符",
    path: "/tools/json-to-csv",
    icon: Table2,
    category: "开发工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "csv-to-json",
    name: "CSV 转 JSON",
    description: "快速将 CSV 表格数据转换为 JSON 数组格式，支持自定义分隔符",
    path: "/tools/csv-to-json",
    icon: Table2,
    category: "开发工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "json-to-xml",
    name: "JSON 转 XML",
    description: "快速将 JSON 数据转换为 XML 格式，自定义根节点名称",
    path: "/tools/json-to-xml",
    icon: Code2,
    category: "开发工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "xml-to-json",
    name: "XML 转 JSON",
    description: "快速将 XML 数据转换为 JSON 格式，支持属性和嵌套结构",
    path: "/tools/xml-to-json",
    icon: Code2,
    category: "开发工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "csv-to-xml",
    name: "CSV 转 XML",
    description: "快速将 CSV 表格数据转换为 XML 格式，自定义节点名称",
    path: "/tools/csv-to-xml",
    icon: Table2,
    category: "开发工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "xml-formatter",
    name: "XML 格式化",
    description: "XML 代码格式化和压缩工具，支持美化和压缩 XML 代码",
    path: "/tools/xml-formatter",
    icon: Code2,
    category: "开发工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "yaml-formatter",
    name: "YAML 格式化",
    description: "YAML 代码格式化工具，统一缩进风格，清理注释和空行",
    path: "/tools/yaml-formatter",
    icon: FileText,
    category: "开发工具",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "sql-formatter",
    name: "SQL 格式化",
    description: "SQL 代码格式化和压缩工具，美化 SQL 语句，支持多种数据库语法",
    path: "/tools/sql-formatter",
    icon: Database,
    category: "开发工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "javascript-formatter",
    name: "JavaScript 格式化",
    description: "JavaScript 代码格式化和压缩工具，美化 JS 代码，一键压缩减小体积",
    path: "/tools/javascript-formatter",
    icon: Code2,
    category: "开发工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "css-formatter",
    name: "CSS 格式化/压缩",
    description: "CSS代码格式化和压缩工具，支持自定义缩进，一键美化和最小化CSS代码",
    path: "/tools/css-formatter",
    icon: Code2,
    category: "开发工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "html-formatter",
    name: "HTML 格式化/压缩",
    description: "HTML代码格式化和压缩工具，支持自定义缩进，一键美化和最小化HTML代码",
    path: "/tools/html-formatter",
    icon: FileCode,
    category: "开发工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "html-entity-encode",
    name: "HTML 实体编码",
    description: "将特殊字符转换为 HTML 实体，防止 XSS 攻击",
    path: "/tools/html-entity-encode",
    icon: FileCode,
    category: "开发工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "html-entity-decode",
    name: "HTML 实体解码",
    description: "将 HTML 实体还原为原始字符",
    path: "/tools/html-entity-decode",
    icon: FileCode,
    category: "开发工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "text-to-binary",
    name: "文本转二进制",
    description: "支持中英文等多语言字符转换为二进制编码",
    path: "/tools/text-to-binary",
    icon: Binary,
    category: "开发工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "binary-to-text",
    name: "二进制转文本",
    description: "支持 UTF-8 编码，将二进制数据转换为可读文本",
    path: "/tools/binary-to-text",
    icon: Binary,
    category: "开发工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "text-to-hex",
    name: "文本转十六进制",
    description: "支持中英文等多语言字符转换为十六进制编码",
    path: "/tools/text-to-hex",
    icon: Hash,
    category: "开发工具",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "hex-to-text",
    name: "十六进制转文本",
    description: "支持 UTF-8 编码，将十六进制数据转换为可读文本",
    path: "/tools/hex-to-text",
    icon: Hash,
    category: "开发工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "url-encode",
    name: "URL 编码",
    description: "URL 编码和解码工具，快速进行 URL 编码，支持中文等特殊字符",
    path: "/tools/url-encode",
    icon: Link,
    category: "开发工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "regex-tester",
    name: "正则表达式测试",
    description: "实时测试正则表达式，高亮匹配结果",
    path: "/tools/regex-tester",
    icon: Regex,
    category: "开发工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "hash-generator",
    name: "哈希生成器",
    description: "MD5、SHA-1、SHA-256等多种哈希算法",
    path: "/tools/hash-generator",
    icon: Hash,
    category: "开发工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum 生成",
    description: "快速生成 Lorem Ipsum 占位文本，用于设计和开发测试",
    path: "/tools/lorem-ipsum",
    icon: FileText,
    category: "开发工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "random-string-generator",
    name: "随机字符串生成",
    description: "支持自定义长度、字符类型和数量，安全加密随机",
    path: "/tools/random-string-generator",
    icon: Shuffle,
    category: "开发工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "text-reverse",
    name: "文本反转",
    description: "支持字符反转、单词反转、行反转多种模式",
    path: "/tools/text-reverse",
    icon: ArrowLeftRight,
    category: "开发工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "text-sort",
    name: "文本行排序",
    description: "支持升序降序、文本数字排序、去重等多种功能",
    path: "/tools/text-sort",
    icon: ArrowUpDown,
    category: "开发工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "text-replace",
    name: "文本批量替换",
    description: "支持普通替换和正则表达式替换，大小写敏感设置",
    path: "/tools/text-replace",
    icon: Replace,
    category: "开发工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "remove-empty-lines",
    name: "删除空行",
    description: "一键移除文本中的空行和空白行，支持只含空格的行",
    path: "/tools/remove-empty-lines",
    icon: Trash,
    category: "开发工具",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "remove-spaces",
    name: "去除多余空格",
    description: "支持多种空格清理模式，快速清理文本中的空白字符",
    path: "/tools/remove-spaces",
    icon: Eraser,
    category: "开发工具",
    color: "from-sky-500 to-cyan-500",
  },
  {
    id: "json-schema-validator",
    name: "JSON Schema 验证",
    description: "校验 JSON 数据是否符合 Schema 规范",
    path: "/tools/json-schema-validator",
    icon: CheckCircle,
    category: "开发工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "json-viewer",
    name: "JSON 树状查看器",
    description: "以可折叠的树形结构展示 JSON 数据，方便浏览复杂嵌套结构",
    path: "/tools/json-viewer",
    icon: FileJson,
    category: "开发工具",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "markdown-to-html",
    name: "Markdown 转 HTML",
    description: "快速将 Markdown 文本转换为 HTML 代码",
    path: "/tools/markdown-to-html",
    icon: FileText,
    category: "开发工具",
    color: "from-indigo-500 to-violet-500",
  },
  {
    id: "html-to-markdown",
    name: "HTML 转 Markdown",
    description: "快速将 HTML 代码转换为 Markdown 文本",
    path: "/tools/html-to-markdown",
    icon: Code2,
    category: "开发工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "css-minifier",
    name: "CSS压缩工具",
    description: "在线CSS代码压缩工具，一键压缩减小CSS文件体积，优化网页加载速度",
    path: "/tools/css-minifier",
    icon: Minimize2,
    category: "开发工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "html-minifier",
    name: "HTML压缩工具",
    description: "在线HTML代码压缩工具，去除空白和注释，减小HTML文件体积",
    path: "/tools/html-minifier",
    icon: Minimize2,
    category: "开发工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "json-minifier",
    name: "JSON压缩工具",
    description: "在线JSON数据压缩工具，一键压缩JSON数据，减小体积便于传输",
    path: "/tools/json-minifier",
    icon: Minimize2,
    category: "开发工具",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "css-prefixer",
    name: "CSS自动加前缀",
    description: "CSS自动添加浏览器前缀，支持-webkit-、-moz-、-ms-、-o-等前缀，兼容多浏览器",
    path: "/tools/css-prefixer",
    icon: Braces,
    category: "开发工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "css-specificity-calculator",
    name: "CSS选择器权重计算",
    description: "计算CSS选择器的特异性权重，了解选择器优先级，帮助优化CSS代码",
    path: "/tools/css-specificity-calculator",
    icon: Scale,
    category: "开发工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "json-diff",
    name: "JSON对比差异",
    description: "在线对比两个JSON数据的差异，高亮显示新增、删除、修改的内容",
    path: "/tools/json-diff",
    icon: GitCompare,
    category: "开发工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "xml-diff",
    name: "XML对比差异",
    description: "在线对比两个XML数据的差异，高亮显示结构和内容的不同",
    path: "/tools/xml-diff",
    icon: GitCompare,
    category: "开发工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "yaml-diff",
    name: "YAML对比差异",
    description: "在线对比两个YAML配置的差异，高亮显示新增、删除、修改的内容",
    path: "/tools/yaml-diff",
    icon: GitCompare,
    category: "开发工具",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "base64-to-image",
    name: "Base64转图片",
    description: "将Base64编码的字符串转换为图片，支持预览和下载，本地处理安全可靠",
    path: "/tools/base64-to-image",
    icon: Image,
    category: "开发工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "jsonpath-tester",
    name: "JSONPath测试器",
    description: "在线测试JSONPath表达式，快速查询JSON数据，支持实时预览查询结果",
    path: "/tools/jsonpath-tester",
    icon: Braces,
    category: "开发工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "xpath-tester",
    name: "XPath测试器",
    description: "在线测试XPath表达式，快速查询XML/HTML文档节点，支持实时预览结果",
    path: "/tools/xpath-tester",
    icon: Code2,
    category: "开发工具",
    color: "from-cyan-500 to-teal-500",
  },
  {
    id: "typescript-formatter",
    name: "TypeScript格式化",
    description: "TypeScript代码格式化工具，美化TS代码，统一代码风格，一键格式化",
    path: "/tools/typescript-formatter",
    icon: FileCode,
    category: "开发工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "php-formatter",
    name: "PHP格式化",
    description: "PHP代码格式化工具，美化PHP代码，统一缩进风格，一键格式化",
    path: "/tools/php-formatter",
    icon: FileCode,
    category: "开发工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "python-formatter",
    name: "Python格式化",
    description: "Python代码格式化工具，美化Python代码，统一代码风格，一键格式化",
    path: "/tools/python-formatter",
    icon: FileCode,
    category: "开发工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "json-to-typescript",
    name: "JSON转TypeScript接口",
    description: "将JSON数据转换为TypeScript接口定义，自动推导类型，一键生成interface",
    path: "/tools/json-to-typescript",
    icon: Braces,
    category: "开发工具",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "json-to-go-struct",
    name: "JSON转Go结构体",
    description: "将JSON数据转换为Go结构体定义，自动推导字段类型，一键生成struct",
    path: "/tools/json-to-go-struct",
    icon: Braces,
    category: "开发工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "json-to-java-class",
    name: "JSON转Java类",
    description: "将JSON数据转换为Java类定义，自动生成getter/setter，一键生成POJO类",
    path: "/tools/json-to-java-class",
    icon: Braces,
    category: "开发工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "json-to-python",
    name: "JSON转Python类",
    description: "将JSON数据转换为Python类定义，自动推导字段类型，一键生成dataclass",
    path: "/tools/json-to-python",
    icon: Braces,
    category: "开发工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "regex-builder",
    name: "正则表达式构建器",
    description: "可视化构建正则表达式，支持常用模式选择，实时测试匹配结果",
    path: "/tools/regex-builder",
    icon: Regex,
    category: "开发工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "regex-cheatsheet",
    name: "正则表达式速查表",
    description: "正则表达式速查表，常用正则语法大全，快速查阅正则表达式参考",
    path: "/tools/regex-cheatsheet",
    icon: BookOpen,
    category: "开发工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "unicode-converter",
    name: "Unicode转换",
    description: "Unicode编码转换工具，支持Unicode编码解码、字符转Unicode、Unicode转字符",
    path: "/tools/unicode-converter",
    icon: Hash,
    category: "开发工具",
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "html-to-jsx",
    name: "HTML转JSX",
    description: "将HTML代码转换为JSX语法，自动转换class/className、style等属性，React开发必备",
    path: "/tools/html-to-jsx",
    icon: Code2,
    category: "开发工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "jsx-to-html",
    name: "JSX转HTML",
    description: "将JSX代码转换为HTML语法，自动转换className/class等属性，快速转换React代码",
    path: "/tools/jsx-to-html",
    icon: FileCode,
    category: "开发工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "ascii-table",
    name: "ASCII码对照表",
    description: "完整ASCII码表查询，支持十进制、十六进制、二进制、字符对照查询，可搜索过滤",
    path: "/tools/ascii-table",
    icon: Hash,
    category: "开发工具",
    color: "from-slate-500 to-zinc-600",
  },
  {
    id: "git-cheatsheet",
    name: "Git命令速查",
    description: "常用Git命令速查表，涵盖提交、分支、远程、撤销等操作，支持搜索快速查找",
    path: "/tools/git-cheatsheet",
    icon: GitBranch,
    category: "开发工具",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "linux-cheatsheet",
    name: "Linux命令速查",
    description: "常用Linux命令速查表，文件、网络、进程、权限等命令大全，支持搜索过滤",
    path: "/tools/linux-cheatsheet",
    icon: Terminal,
    category: "开发工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "http-status-codes",
    name: "HTTP状态码查询",
    description: "HTTP状态码大全查询，1xx/2xx/3xx/4xx/5xx状态码含义详解，支持搜索",
    path: "/tools/http-status-codes",
    icon: Globe,
    category: "开发工具",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "mime-types",
    name: "MIME类型查询",
    description: "MIME类型对照表，常用文件扩展名对应的MIME类型查询，支持双向搜索",
    path: "/tools/mime-types",
    icon: FileType,
    category: "开发工具",
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "base32-encoder",
    name: "Base32编解码",
    description: "Base32编码和解码工具，支持文本和字符串的Base32转换，实时转换",
    path: "/tools/base32-encoder",
    icon: Binary,
    category: "开发工具",
    color: "from-teal-500 to-emerald-500",
  },
  {
    id: "base58-encoder",
    name: "Base58编解码",
    description: "Base58编码和解码工具，比特币地址编码，支持编码解码双向转换",
    path: "/tools/base58-encoder",
    icon: Binary,
    category: "开发工具",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "jwt-decoder",
    name: "JWT解析器",
    description: "JWT Token在线解析，解码Header和Payload，验证签名格式，支持HS256算法",
    path: "/tools/jwt-decoder",
    icon: KeyRound,
    category: "开发工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "cron-generator",
    name: "Cron表达式生成器",
    description: "可视化Cron表达式生成器，支持分钟/小时/日/月/周设置，实时生成表达式",
    path: "/tools/cron-generator",
    icon: CalendarClock,
    category: "开发工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "graphql-formatter",
    name: "GraphQL格式化",
    description: "GraphQL查询格式化和美化工具，自动缩进格式化、压缩、语法高亮",
    path: "/tools/graphql-formatter",
    icon: Braces,
    category: "开发工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "markdown-table-generator",
    name: "Markdown表格生成器",
    description: "可视化生成Markdown表格，支持自定义行列数、对齐方式，一键复制",
    path: "/tools/markdown-table-generator",
    icon: Table2,
    category: "开发工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "uuid-decoder",
    name: "UUID解码器",
    description: "UUID解析器，解析UUID版本、变体、时间戳等信息，支持UUID v1/v4等版本",
    path: "/tools/uuid-decoder",
    icon: Fingerprint,
    category: "开发工具",
    color: "from-cyan-500 to-teal-500",
  },

  // 图片工具
  {
    id: "image-compressor",
    name: "图片压缩工具",
    description: "在线图片压缩，支持JPG/PNG/WebP，调整质量压缩后下载，节省存储空间",
    path: "/tools/image-compressor",
    icon: ImageDown,
    category: "图片工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "image-converter",
    name: "图片格式转换",
    description: "图片格式互转，支持JPG、PNG、WebP、BMP等多种格式，批量转换",
    path: "/tools/image-converter",
    icon: ImagePlus,
    category: "图片工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "image-to-pdf",
    name: "图片转PDF",
    description: "将图片转换为PDF文件，支持单图/多图合并PDF，调整页面大小",
    path: "/tools/image-to-pdf",
    icon: FileImage,
    category: "图片工具",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "avatar-generator",
    name: "头像生成器",
    description: "生成个性化头像，文字头像、渐变背景、多种配色方案，一键下载",
    path: "/tools/avatar-generator",
    icon: User,
    category: "图片工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "image-watermark",
    name: "图片加水印",
    description: "给图片添加文字或图片水印，支持位置选择、透明度调节、旋转",
    path: "/tools/image-watermark",
    icon: Droplets,
    category: "图片工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "image-crop",
    name: "图片裁剪工具",
    description: "在线图片裁剪，支持自由裁剪和固定比例裁剪，拖拽调整裁剪框，实时预览，一键下载",
    path: "/tools/image-crop",
    icon: Crop,
    category: "图片工具",
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "image-rotate",
    name: "图片旋转翻转",
    description: "在线图片旋转和翻转，支持任意角度旋转、水平垂直翻转，实时预览，一键下载",
    path: "/tools/image-rotate",
    icon: RotateCw,
    category: "图片工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "image-resize",
    name: "图片调整大小",
    description: "在线调整图片尺寸，支持像素和百分比缩放，锁定宽高比，多格式输出",
    path: "/tools/image-resize",
    icon: Maximize2,
    category: "图片工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "text-to-image",
    name: "文字转图片",
    description: "将文字转换为图片，自定义字体颜色背景，多种预设样式，社交媒体配图一键生成",
    path: "/tools/text-to-image",
    icon: Type,
    category: "图片工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "image-blur",
    name: "图片模糊像素化",
    description: "图片高斯模糊和马赛克像素化处理，支持强度调节和局部模糊，实时预览",
    path: "/tools/image-blur",
    icon: Sparkles,
    category: "图片工具",
    color: "from-slate-500 to-gray-600",
  },
  {
    id: "business-card",
    name: "名片生成器",
    description: "在线生成电子名片图片，多种模板风格，自定义配色，一键下载",
    path: "/tools/business-card",
    icon: Contact,
    category: "图片工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "image-grid",
    name: "图片拼接/长图",
    description: "多张图片横向纵向拼接，支持自定义间距、背景色、圆角，一键生成长图",
    path: "/tools/image-grid",
    icon: Layers,
    category: "图片工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "image-grid-cutter",
    name: "九宫格切图",
    description: "图片切成九宫格，支持多种网格和圆形裁剪，社交媒体发图必备",
    path: "/tools/image-grid-cutter",
    icon: Grid2x2,
    category: "图片工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "screenshot-maker",
    name: "截图美化",
    description: "给截图添加圆角、阴影、渐变背景和设备外壳，制作精美展示图",
    path: "/tools/screenshot-maker",
    icon: Monitor,
    category: "图片工具",
    color: "from-sky-500 to-blue-500",
  },
  {
    id: "meme-generator",
    name: "表情包生成器",
    description: "给图片加文字制作表情包，支持多种模板，自定义字体颜色描边",
    path: "/tools/meme-generator",
    icon: Smile,
    category: "图片工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "bg-remover",
    name: "图片抠图",
    description: "一键移除图片背景，支持多种抠图模式和边缘羽化，生成透明背景图",
    path: "/tools/bg-remover",
    icon: Eraser,
    category: "图片工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "circle-crop",
    name: "圆形头像裁剪",
    description: "将图片裁剪为圆形/圆角/六边形头像，支持边框美化，一键下载",
    path: "/tools/circle-crop",
    icon: Circle,
    category: "图片工具",
    color: "from-pink-500 to-rose-500",
  },

  // 格式转换类
  {
    id: "png-to-jpg",
    name: "PNG转JPG",
    description: "在线将PNG图片转换为JPG格式，支持自定义质量，本地处理安全可靠",
    path: "/tools/png-to-jpg",
    icon: ImagePlus,
    category: "图片工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "jpg-to-png",
    name: "JPG转PNG",
    description: "在线将JPG图片转换为PNG格式，支持透明背景，无损转换",
    path: "/tools/jpg-to-png",
    icon: ImagePlus,
    category: "图片工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "webp-to-png",
    name: "WebP转PNG",
    description: "在线将WebP图片转换为PNG格式，支持透明通道，高质量转换",
    path: "/tools/webp-to-png",
    icon: ImagePlus,
    category: "图片工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "image-to-webp",
    name: "图片转WebP",
    description: "在线将图片转换为WebP格式，高压缩率高质量，大幅减小图片体积",
    path: "/tools/image-to-webp",
    icon: ImageDown,
    category: "图片工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "image-to-bmp",
    name: "图片转BMP",
    description: "在线将图片转换为BMP位图格式，无损位图格式，兼容老旧系统",
    path: "/tools/image-to-bmp",
    icon: FileImage,
    category: "图片工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "image-to-ico",
    name: "图片转ICO图标",
    description: "在线将图片转换为ICO图标格式，支持多种尺寸，适用于网站favicon",
    path: "/tools/image-to-ico",
    icon: Image,
    category: "图片工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "svg-to-png",
    name: "SVG转PNG",
    description: "在线将SVG矢量图转换为PNG位图，支持自定义尺寸和背景色，高清输出",
    path: "/tools/svg-to-png",
    icon: FileImage,
    category: "图片工具",
    color: "from-pink-500 to-rose-500",
  },

  // 图片编辑/滤镜类
  {
    id: "image-flip",
    name: "图片翻转工具",
    description: "在线翻转图片，支持水平翻转和垂直翻转，实时预览效果，一键下载",
    path: "/tools/image-flip",
    icon: FlipHorizontal,
    category: "图片工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "image-grayscale",
    name: "图片黑白/灰度",
    description: "在线将图片转为黑白灰度效果，支持灰度强度调节，经典黑白滤镜",
    path: "/tools/image-grayscale",
    icon: Droplets,
    category: "图片工具",
    color: "from-slate-500 to-gray-600",
  },
  {
    id: "image-sharpen",
    name: "图片锐化",
    description: "在线图片锐化处理，增强图片清晰度和边缘细节，让模糊图片变清晰",
    path: "/tools/image-sharpen",
    icon: Sparkles,
    category: "图片工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "image-sepia",
    name: "图片复古怀旧",
    description: "在线给图片添加复古怀旧滤镜，经典棕褐色调，老照片效果",
    path: "/tools/image-sepia",
    icon: Palette,
    category: "图片工具",
    color: "from-amber-600 to-yellow-600",
  },
  {
    id: "image-invert",
    name: "图片反色",
    description: "在线图片颜色反转，负片效果，所有颜色取反，创造独特视觉效果",
    path: "/tools/image-invert",
    icon: Contrast,
    category: "图片工具",
    color: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "image-brightness",
    name: "图片亮度调整",
    description: "在线调整图片亮度，支持增加和降低亮度，实时预览效果",
    path: "/tools/image-brightness",
    icon: Sun,
    category: "图片工具",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "image-contrast",
    name: "图片对比度调整",
    description: "在线调整图片对比度，增强或降低对比，让图片更有层次感",
    path: "/tools/image-contrast",
    icon: Contrast,
    category: "图片工具",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "image-saturation",
    name: "图片饱和度调整",
    description: "在线调整图片饱和度，增强色彩鲜艳度或转为黑白，自由控制色彩浓度",
    path: "/tools/image-saturation",
    icon: Palette,
    category: "图片工具",
    color: "from-pink-500 to-rose-500",
  },

  // 其他图片工具
  {
    id: "image-collage",
    name: "图片拼接",
    description: "在线多张图片拼接，支持横向和纵向拼接，自定义间距和背景色",
    path: "/tools/image-collage",
    icon: Layers,
    category: "图片工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "image-splitter",
    name: "图片分割九宫格",
    description: "在线图片九宫格分割，将一张图切成多块，社交媒体发图必备",
    path: "/tools/image-splitter",
    icon: Grid2x2,
    category: "图片工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "image-border",
    name: "图片加边框",
    description: "在线给图片添加边框，自定义边框颜色、宽度和圆角，美化图片",
    path: "/tools/image-border",
    icon: Square,
    category: "图片工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "image-round",
    name: "图片圆角/圆形裁剪",
    description: "在线给图片添加圆角或裁剪为圆形，自定义圆角大小，头像制作必备",
    path: "/tools/image-round",
    icon: Circle,
    category: "图片工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "barcode-generator",
    name: "条形码生成器",
    description: "在线生成条形码，支持多种码制，自定义尺寸和颜色，一键下载",
    path: "/tools/barcode-generator",
    icon: Barcode,
    category: "图片工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "favicon-generator",
    name: "Favicon生成器",
    description: "从图片生成多种尺寸的favicon图标，适用于网站和应用",
    path: "/tools/favicon-generator",
    icon: Image,
    category: "图片工具",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "placeholder-image",
    name: "占位图生成器",
    description: "快速生成占位图片，自定义尺寸、颜色、文字，用于设计原型开发",
    path: "/tools/placeholder-image",
    icon: ImagePlus,
    category: "图片工具",
    color: "from-slate-500 to-gray-600",
  },
  {
    id: "qr-code-logo",
    name: "带Logo二维码生成",
    description: "生成带Logo的二维码，自定义颜色和尺寸，支持Logo上传和大小调整",
    path: "/tools/qr-code-logo",
    icon: QrCode,
    category: "图片工具",
    color: "from-teal-500 to-emerald-500",
  },
  {
    id: "image-pixelate",
    name: "图片像素化/马赛克",
    description: "将图片转换为像素艺术风格或添加马赛克效果，支持像素大小调节和局部打码",
    path: "/tools/image-pixelate",
    icon: Grid3X3,
    category: "图片工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "image-sketch",
    name: "图片素描效果",
    description: "将图片转换为铅笔素描风格，支持线条粗细和细节调节，一键生成艺术素描",
    path: "/tools/image-sketch",
    icon: PenLine,
    category: "图片工具",
    color: "from-slate-500 to-zinc-600",
  },
  {
    id: "image-cartoon",
    name: "图片卡通化",
    description: "将照片转换为卡通动漫风格，支持多种卡通效果调节，一键生成卡通头像",
    path: "/tools/image-cartoon",
    icon: Smile,
    category: "图片工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "image-vintage",
    name: "图片复古效果",
    description: "给图片添加复古怀旧滤镜，模拟老照片效果，支持多种复古风格和强度调节",
    path: "/tools/image-vintage",
    icon: Sun,
    category: "图片工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "image-fisheye",
    name: "图片鱼眼效果",
    description: "给图片添加鱼眼镜头效果，模拟广角畸变，支持强度调节和多种畸变模式",
    path: "/tools/image-fisheye",
    icon: Aperture,
    category: "图片工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "image-radial-blur",
    name: "图片径向模糊",
    description: "给图片添加径向模糊/缩放模糊效果，模拟速度感和爆炸感，支持中心点调节",
    path: "/tools/image-radial-blur",
    icon: Focus,
    category: "图片工具",
    color: "from-indigo-500 to-violet-500",
  },
  {
    id: "image-tilt-shift",
    name: "图片移轴效果",
    description: "将普通照片转换为微缩模型效果，模拟移轴镜头，支持模糊区域和强度调节",
    path: "/tools/image-tilt-shift",
    icon: Layers,
    category: "图片工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "image-denoise",
    name: "图片降噪",
    description: "去除图片噪点，提升图片清晰度，支持降噪强度调节，让模糊图片变清晰",
    path: "/tools/image-denoise",
    icon: Sparkles,
    category: "图片工具",
    color: "from-sky-500 to-blue-500",
  },

  // PDF工具
  {
    id: "pdf-splitter",
    name: "PDF分割工具",
    description: "在线将PDF文件分割为多个文件，支持按页数分割和指定范围分割，本地处理安全可靠",
    path: "/tools/pdf-splitter",
    icon: Scissors,
    category: "PDF工具",
    color: "from-rose-500 to-red-500",
  },
  {
    id: "word-to-pdf",
    name: "Word转PDF",
    description: "在线将Word文档转换为PDF格式，支持doc/docx，本地处理安全可靠",
    path: "/tools/word-to-pdf",
    icon: FileText,
    category: "PDF工具",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "pdf-to-word",
    name: "PDF转Word",
    description: "在线将PDF文件转换为Word文档，提取文本内容，支持编辑和下载",
    path: "/tools/pdf-to-word",
    icon: FileType,
    category: "PDF工具",
    color: "from-indigo-500 to-blue-500",
  },
  {
    id: "pdf-to-image",
    name: "PDF转图片",
    description: "在线将PDF每页转换为图片，支持JPG/PNG格式，高质量输出，批量下载",
    path: "/tools/pdf-to-image",
    icon: FileImage,
    category: "PDF工具",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "pdf-to-text",
    name: "PDF转文本",
    description: "在线提取PDF中的文本内容，支持复制和下载，本地处理安全可靠",
    path: "/tools/pdf-to-text",
    icon: FileText,
    category: "PDF工具",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "text-to-pdf",
    name: "文本转PDF",
    description: "在线将文本内容转换为PDF文件，支持自定义字体、页面大小和边距",
    path: "/tools/text-to-pdf",
    icon: FileOutput,
    category: "PDF工具",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "html-to-pdf",
    name: "HTML转PDF",
    description: "在线将HTML代码转换为PDF文件，支持粘贴HTML或输入URL，一键生成",
    path: "/tools/html-to-pdf",
    icon: FileCode,
    category: "PDF工具",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "pdf-rotate",
    name: "PDF页面旋转",
    description: "在线旋转PDF页面，支持90度/180度/270度旋转，可选择指定页面",
    path: "/tools/pdf-rotate",
    icon: RotateCw,
    category: "PDF工具",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "pdf-protect",
    name: "PDF加密保护",
    description: "在线为PDF文件添加密码保护，设置打开密码和权限密码，安全可靠",
    path: "/tools/pdf-protect",
    icon: Lock,
    category: "PDF工具",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "pdf-unlock",
    name: "PDF解锁",
    description: "在线移除PDF文件的密码保护，输入密码后解锁下载",
    path: "/tools/pdf-unlock",
    icon: Unlock,
    category: "PDF工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "pdf-sign",
    name: "PDF电子签名",
    description: "在线为PDF添加电子签名，支持手写签名和文字签名，一键添加",
    path: "/tools/pdf-sign",
    icon: PenLine,
    category: "PDF工具",
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "pdf-split-pages",
    name: "PDF按页分割",
    description: "将PDF的每一页单独保存为一个文件，一键批量分割下载",
    path: "/tools/pdf-split-pages",
    icon: LayoutList,
    category: "PDF工具",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "pdf-extract-pages",
    name: "PDF提取页面",
    description: "从PDF中提取指定页面，支持页码范围选择，提取后另存为新PDF",
    path: "/tools/pdf-extract-pages",
    icon: FileStack,
    category: "PDF工具",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "pdf-reorder-pages",
    name: "PDF页面重排",
    description: "在线调整PDF页面顺序，拖拽排序，一键生成新PDF文件",
    path: "/tools/pdf-reorder-pages",
    icon: ArrowUpDown,
    category: "PDF工具",
    color: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "pdf-to-excel",
    name: "PDF转Excel",
    description: "在线从PDF中提取表格数据并转换为Excel格式，支持复制和下载",
    path: "/tools/pdf-to-excel",
    icon: FileSpreadsheet,
    category: "PDF工具",
    color: "from-emerald-500 to-green-500",
  },
  {
    id: "excel-to-pdf",
    name: "Excel转PDF",
    description: "在线将Excel表格转换为PDF文件，支持xlsx格式，保持表格格式",
    path: "/tools/excel-to-pdf",
    icon: FileSpreadsheet,
    category: "PDF工具",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "ppt-to-pdf",
    name: "PPT转PDF",
    description: "在线将PPT演示文稿转换为PDF文件，支持pptx格式，保持排版效果",
    path: "/tools/ppt-to-pdf",
    icon: FileText,
    category: "PDF工具",
    color: "from-orange-500 to-red-500",
  },

  // 视频音频工具
  {
    id: "video-compressor",
    name: "视频压缩",
    description: "在线压缩视频文件大小，支持调整分辨率、比特率和质量，本地处理",
    path: "/tools/video-compressor",
    icon: Video,
    category: "视频音频",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "audio-compressor",
    name: "音频压缩",
    description: "在线压缩音频文件大小，支持调整比特率和质量，多种格式输出",
    path: "/tools/audio-compressor",
    icon: Music,
    category: "视频音频",
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "mp4-to-mp3",
    name: "MP4转MP3",
    description: "在线从MP4视频中提取音频并转换为MP3格式，一键转换下载",
    path: "/tools/mp4-to-mp3",
    icon: Disc,
    category: "视频音频",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "audio-extractor",
    name: "视频提取音频",
    description: "在线从视频中提取音频轨道，支持MP3/WAV/WebM等多种音频格式",
    path: "/tools/audio-extractor",
    icon: Mic,
    category: "视频音频",
    color: "from-pink-500 to-fuchsia-500",
  },
  {
    id: "video-trimmer",
    name: "视频裁剪",
    description: "在线裁剪视频片段，精确控制起止时间，支持预览和导出",
    path: "/tools/video-trimmer",
    icon: Scissors,
    category: "视频音频",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "audio-trimmer",
    name: "音频裁剪",
    description: "在线裁剪音频片段，精确控制起止时间，支持淡入淡出效果",
    path: "/tools/audio-trimmer",
    icon: Scissors,
    category: "视频音频",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "video-merger",
    name: "视频合并",
    description: "在线合并多个视频文件，支持不同格式，拖拽排序，一键合并",
    path: "/tools/video-merger",
    icon: Film,
    category: "视频音频",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "audio-merger",
    name: "音频合并",
    description: "在线合并多个音频文件，支持不同格式，可调整顺序和添加间隔",
    path: "/tools/audio-merger",
    icon: Music,
    category: "视频音频",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "video-to-webm",
    name: "视频转WebM",
    description: "在线将视频转换为WebM格式，高压缩率高质量，大幅减小体积",
    path: "/tools/video-to-webm",
    icon: Video,
    category: "视频音频",
    color: "from-teal-500 to-cyan-500",
  },
  {
    id: "video-speed-changer",
    name: "视频变速",
    description: "在线调整视频播放速度，支持0.25x-4x变速，保持音频同步",
    path: "/tools/video-speed-changer",
    icon: FastForward,
    category: "视频音频",
    color: "from-amber-500 to-orange-500",
  },
  {
    id: "audio-speed-changer",
    name: "音频变速",
    description: "在线调整音频播放速度，支持0.25x-4x变速，可保持音调不变",
    path: "/tools/audio-speed-changer",
    icon: FastForward,
    category: "视频音频",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "video-reverse",
    name: "视频倒放",
    description: "在线将视频倒放播放，一键生成倒放效果，创意视频制作工具",
    path: "/tools/video-reverse",
    icon: Rewind,
    category: "视频音频",
    color: "from-rose-500 to-red-500",
  },
  {
    id: "audio-reverse",
    name: "音频倒放",
    description: "在线将音频倒放播放，一键生成倒放效果，趣味音频处理工具",
    path: "/tools/audio-reverse",
    icon: Rewind,
    category: "视频音频",
    color: "from-fuchsia-500 to-purple-500",
  },
  {
    id: "volume-changer",
    name: "音量调整",
    description: "在线调整音频音量大小，支持增大和减小音量，精确控制分贝",
    path: "/tools/volume-changer",
    icon: Volume2,
    category: "视频音频",
    color: "from-cyan-500 to-teal-500",
  },
];

export const categories = [
  { id: "all", name: "全部工具", slug: "all", icon: Grid3X3 },
  { id: "计算工具", name: "计算工具", slug: "calculator", icon: Calculator },
  { id: "文本工具", name: "文本工具", slug: "text", icon: FileText },
  { id: "生成工具", name: "生成工具", slug: "generator", icon: Sparkles },
  { id: "转换工具", name: "转换工具", slug: "converter", icon: ArrowUpDown },
  { id: "设计工具", name: "设计工具", slug: "design", icon: Palette },
  { id: "图片工具", name: "图片工具", slug: "image", icon: Image },
  { id: "生活工具", name: "生活工具", slug: "life", icon: Home },
  { id: "开发工具", name: "开发工具", slug: "developer", icon: Code2 },
  { id: "PDF工具", name: "PDF工具", slug: "pdf", icon: FileText },
  { id: "视频音频", name: "视频音频", slug: "video-audio", icon: Film },
];

// Get category info by slug
export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug);
}

// Get category slug by name
export function getCategorySlugByName(name: string): string {
  const cat = categories.find((c) => c.name === name);
  return cat?.slug || "";
}

// Get all tools
export function getAllTools(): Tool[] {
  return tools;
}

// Get tools by category name
export function getToolsByCategory(categoryName: string): Tool[] {
  if (categoryName === "全部工具") return tools;
  return tools.filter((t) => t.category === categoryName);
}

// Get popular tools (first 8)
export function getPopularTools(): Tool[] {
  return tools.slice(0, 8);
}

// Get tool by slug/id
export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.id === slug);
}

// 热门标签列表 - SEO内链核心
export const popularTags = [
  { name: "JSON", slug: "json", count: 12 },
  { name: "图片压缩", slug: "image-compress", count: 8 },
  { name: "PDF转换", slug: "pdf-convert", count: 15 },
  { name: "在线计算", slug: "calculator", count: 20 },
  { name: "文本处理", slug: "text-processing", count: 18 },
  { name: "编码解码", slug: "encode-decode", count: 10 },
  { name: "二维码", slug: "qrcode", count: 5 },
  { name: "密码生成", slug: "password", count: 3 },
  { name: "正则表达式", slug: "regex", count: 4 },
  { name: "单位换算", slug: "unit-converter", count: 6 },
  { name: "图片编辑", slug: "image-editor", count: 15 },
  { name: "视频处理", slug: "video", count: 8 },
  { name: "音频处理", slug: "audio", count: 8 },
  { name: "颜色工具", slug: "color", count: 10 },
  { name: "CSS工具", slug: "css", count: 8 },
  { name: "房贷计算", slug: "mortgage", count: 2 },
  { name: "个税计算", slug: "tax", count: 2 },
  { name: "日期计算", slug: "date", count: 5 },
  { name: "随机生成", slug: "random", count: 6 },
  { name: "格式化", slug: "formatter", count: 8 },
];

// 根据工具自动提取标签
export function getToolTags(tool: Tool): string[] {
  if (tool.tags && tool.tags.length > 0) return tool.tags;

  const tags: string[] = [];
  const name = tool.name.toLowerCase();
  const desc = tool.description.toLowerCase();

  // 关键词匹配生成标签
  const tagRules: Record<string, string[]> = {
    json: ["json"],
    "image-compress": ["压缩", "图片压缩"],
    "pdf-convert": ["pdf"],
    calculator: ["计算", "计算器"],
    "text-processing": ["文本", "文字"],
    "encode-decode": ["编码", "解码", "base64", "base", "进制"],
    qrcode: ["二维码", "qr"],
    password: ["密码"],
    regex: ["正则"],
    "unit-converter": ["换算", "转换"],
    "image-editor": ["图片", "图像"],
    video: ["视频"],
    audio: ["音频", "音乐", "声音"],
    color: ["颜色", "色彩"],
    css: ["css"],
    mortgage: ["房贷"],
    tax: ["个税", "税"],
    date: ["日期", "时间"],
    random: ["随机"],
    formatter: ["格式化", "美化"],
  };

  for (const [tag, keywords] of Object.entries(tagRules)) {
    if (keywords.some((kw) => name.includes(kw) || desc.includes(kw))) {
      tags.push(tag);
    }
  }

  // 至少返回1个标签，最多4个
  if (tags.length === 0) tags.push("online-tools");
  return tags.slice(0, 4);
}

// 根据标签获取工具
export function getToolsByTag(tagSlug: string): Tool[] {
  return tools.filter((tool) => {
    const toolTags = getToolTags(tool);
    return toolTags.includes(tagSlug);
  });
}

// 获取标签名称
export function getTagName(slug: string): string {
  const tag = popularTags.find((t) => t.slug === slug);
  if (tag) return tag.name;
  // fallback: 从slug生成名称
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
